In [1]:
#Load libraries
import warnings
warnings.filterwarnings("ignore")
import numpy as np
import pandas as pd
from ctgan import CTGAN

In [7]:
FUNCTIONS_HOME = '../../../functions/evaluation_functions/' #home directory of the project
REAL_DATA_HOME = '../../../data/raw/rembrandt/' #home directory of the project
SYN_DATA_HOME  = '../../../data/processed/rembrandt/' #home directory of the project
TRAIN_FILE = '0_Depression_Data_Real_Train.csv'
SYNTHETIC_FILE = '0_Depression_Data_Synthetic_CTGAN.csv'

## 1. Load the dataset

In [8]:
real_data = pd.read_csv(REAL_DATA_HOME + TRAIN_FILE)
real_data

,group,ma1,hars1,ma2,hars2,ma3,hars3,ma4,hars4,ma5,...,ma10,hars10,ma11,hars11,ma12,hars12,ma13,hars13,ma14,hars14
0,Control,-0.872369,-0.943320,-0.872369,-0.943320,-0.872369,-1.130271,-0.872369,-0.943320,-0.872369,...,-0.872369,-0.943320,-0.872369,-1.130271,-0.872369,-1.130271,-0.497156,-0.756370,-0.872369,-0.943320
1,Remitted,0.628481,0.926183,-0.309550,-0.569420,0.816087,-0.569420,0.816087,-0.382469,2.504542,...,2.316936,1.487034,2.879754,0.926183,2.316936,0.926183,1.378905,0.552282,1.003693,-0.008569
2,Remitted,-0.121944,-0.195519,-0.872369,-0.756370,-0.497156,-0.008569,-0.121944,-0.008569,-0.497156,...,-0.497156,-0.756370,0.440874,-0.195519,-0.497156,-0.195519,0.253268,-0.756370,0.816087,0.739233
3,Remitted,0.816087,0.739233,-0.309550,-0.569420,-0.121944,0.739233,-0.684762,-0.569420,-0.684762,...,-0.497156,-0.756370,-0.684762,-0.943320,-0.684762,-0.756370,-0.497156,-0.943320,-0.497156,0.178382
4,Remitted,1.003693,2.047885,0.253268,2.234835,0.628481,1.487034,1.003693,2.234835,1.754117,...,2.129330,3.543488,1.191299,0.739233,1.754117,1.860935,0.816087,0.739233,-0.497156,1.673984
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,Control,-0.872369,-0.382469,-0.309550,0.178382,-0.684762,-0.756370,-0.872369,-1.130271,-0.121944,...,-0.684762,-0.382469,-0.872369,-0.756370,-0.684762,-0.943320,-0.872369,-0.943320,-0.309550,0.926183
92,Control,-0.872369,-0.569420,-0.684762,-0.195519,-0.872369,-0.756370,-0.872369,-0.569420,-0.872369,...,-0.872369,-0.008569,-0.872369,-0.008569,-0.872369,-0.008569,-0.872369,-0.569420,-0.684762,0.178382
93,Control,-0.684762,-0.943320,-0.684762,-0.756370,-0.497156,-0.943320,-0.121944,-0.756370,-0.872369,...,-0.497156,-0.943320,-0.684762,-0.943320,-0.872369,-0.943320,-0.872369,-0.943320,-0.872369,-0.569420
94,Control,-0.684762,-0.756370,-0.872369,-0.756370,-0.872369,-0.943320,-0.872369,-0.008569,-0.497156,...,-0.684762,0.365332,-0.684762,-1.130271,-0.684762,-1.130271,-0.872369,-0.943320,-0.309550,0.365332
95,Remitted,-0.684762,-0.569420,-0.309550,-0.756370,-0.121944,-0.008569,-0.309550,-0.008569,-0.121944,...,-0.309550,-0.569420,-0.872369,-0.943320,0.628481,0.552282,-0.497156,-0.569420,-0.497156,0.178382

In [ ]:
real_data.dtypes

In [10]:
discrete_columns = ['group']
discrete_columns

['group']

In [12]:
ctgan = CTGAN()
ctgan.fit(real_data, discrete_columns)

In [13]:
synthetic_data = ctgan.sample(len(real_data))
synthetic_data

,group,ma1,hars1,ma2,hars2,ma3,hars3,ma4,hars4,ma5,...,ma10,hars10,ma11,hars11,ma12,hars12,ma13,hars13,ma14,hars14
0,Control,-1.003556,-0.226949,-0.360741,1.665643,-0.374173,-0.719837,0.117326,-0.059717,-1.060621,...,1.997617,2.209913,-0.805324,-1.343262,-1.210574,-0.859809,-1.474385,-0.257095,-0.645991,1.065644
1,Remitted,-0.527101,-0.209512,-0.755790,0.517736,0.427923,-0.264881,1.132112,-2.300370,4.194925,...,-0.855932,1.849551,2.977862,-0.740115,-0.387391,0.117365,-0.928756,1.768706,-0.526334,-1.453899
2,Control,-0.706105,-1.456352,-0.033474,3.599761,2.625076,-0.445736,2.877741,-1.133792,2.610473,...,-0.567815,1.155937,-1.018540,4.231028,-0.746965,-0.838060,-1.064316,1.336957,-0.862144,-1.000972
3,Control,-1.147055,0.339980,0.068270,-0.434389,1.362031,0.769278,1.005867,-1.062024,2.442056,...,-0.494691,-1.840407,-0.478278,-0.620337,0.467659,-1.537834,-0.651787,0.282659,0.371402,0.513703
4,Control,-0.058185,-0.736248,1.374066,0.088680,0.535779,0.252779,2.635707,-1.226003,-0.546500,...,-0.813242,-0.490979,-0.340536,-0.563108,-0.831039,-1.090361,0.337101,1.441900,0.230506,0.416467
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,Control,-1.268920,1.441439,-0.408406,-0.002770,-1.242248,-1.253781,-0.430132,-0.807286,3.074015,...,2.308607,-1.260471,1.039893,-1.914381,-1.068055,-0.770923,0.053616,-0.215893,0.484578,1.196593
92,Remitted,-0.785475,-0.020996,-0.637153,-0.491999,-1.147190,0.525333,4.593586,1.055464,3.412927,...,-0.249155,4.238194,2.395894,-0.844417,-1.002109,0.707884,-1.050444,0.304690,0.016266,2.738263
93,Control,0.203743,-0.691457,-0.349035,0.064769,2.319464,-1.106602,1.233028,-0.404369,0.794581,...,-0.323307,-1.148934,-0.297931,-0.755385,-0.724639,-0.422440,-0.892635,-0.243411,0.727578,0.991291
94,Remitted,-0.474835,-0.425688,-0.143483,0.513089,0.617330,1.602350,-0.641298,0.271874,0.064736,...,1.166148,2.566697,-0.556327,-1.385773,-0.428820,-0.678955,-0.985812,-0.494861,-1.001289,-1.666044
95,Remitted,0.211628,-0.908148,-0.764098,2.192874,-0.087136,-1.155783,1.883427,-0.525599,2.177610,...,-0.715902,-0.551522,4.030542,-1.493387,-0.714806,1.201556,-1.331778,0.146733,-1.140095,1.318775

In [14]:
real_data.describe()

,ma1,hars1,ma2,hars2,ma3,hars3,ma4,hars4,ma5,hars5,...,ma10,hars10,ma11,hars11,ma12,hars12,ma13,hars13,ma14,hars14
count,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,...,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000
mean,-0.139532,-0.092307,-0.270466,-0.236414,0.102793,0.098538,0.110609,0.110223,0.188779,0.172540,...,0.053937,0.125802,-0.071134,-0.168255,-0.037912,-0.164361,-0.235289,-0.366890,-0.008599,0.345858
std,0.603834,0.845636,0.514261,0.832629,0.983578,1.014129,0.945601,0.996333,1.158028,1.165597,...,1.162812,1.101414,1.170961,1.025757,1.116340,1.071261,0.774467,0.719553,0.736712,0.722519
min,-0.872369,-1.130271,-0.872369,-1.130271,-0.872369,-1.130271,-0.872369,-1.130271,-0.872369,-1.130271,...,-0.872369,-1.130271,-0.872369,-1.130271,-0.872369,-1.130271,-0.872369,-1.130271,-0.872369,-1.130271
25%,-0.684762,-0.756370,-0.684762,-0.756370,-0.684762,-0.756370,-0.684762,-0.569420,-0.684762,-0.756370,...,-0.544058,-0.569420,-0.684762,-0.943320,-0.684762,-0.943320,-0.872369,-0.943320,-0.497156,-0.008569
50%,-0.309550,-0.382469,-0.309550,-0.569420,-0.121944,-0.195519,-0.121944,-0.195519,-0.215747,-0.008569,...,-0.497156,-0.195519,-0.684762,-0.569420,-0.497156,-0.569420,-0.497156,-0.569420,-0.121944,0.365332
75%,0.300170,0.552282,-0.121944,0.178382,0.628481,0.739233,0.487776,0.552282,0.628481,0.739233,...,0.300170,0.552282,0.253268,0.552282,0.253268,0.412070,0.065662,-0.195519,0.253268,0.739233
max,1.378905,2.047885,1.003693,3.543488,3.817785,3.356537,3.254966,2.982637,4.943422,3.917388,...,4.192997,4.104339,4.568209,3.356537,4.568209,4.291289,3.254966,2.234835,2.879754,2.982637

In [15]:
synthetic_data.describe()

,ma1,hars1,ma2,hars2,ma3,hars3,ma4,hars4,ma5,hars5,...,ma10,hars10,ma11,hars11,ma12,hars12,ma13,hars13,ma14,hars14
count,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,...,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000
mean,-0.689625,0.267239,-0.271460,0.523379,0.043009,-0.374285,0.839327,-0.593114,1.250429,0.445603,...,-0.208561,0.325780,0.216986,-0.616105,-0.147567,-0.249780,-1.042259,0.335204,0.066612,0.687022
std,0.564340,1.074838,0.488869,1.073332,1.100605,1.058970,1.555381,0.935823,1.754268,1.407747,...,1.156753,1.737519,1.486850,1.190402,1.366222,1.034093,0.536408,0.922171,0.810740,1.104765
min,-1.576501,-1.607697,-0.907135,-0.833060,-2.099525,-1.847750,-1.138502,-2.300370,-1.503641,-2.364752,...,-2.277292,-2.254270,-2.099298,-2.139451,-1.408890,-1.720019,-2.350227,-1.431558,-1.325997,-1.666044
25%,-1.087789,-0.489851,-0.570656,-0.223295,-0.717451,-1.131049,-0.339012,-1.176680,0.058868,-0.446962,...,-0.915665,-0.903184,-0.701798,-1.330697,-0.923158,-0.959723,-1.351343,-0.246832,-0.513852,0.087746
50%,-0.784913,0.155134,-0.309705,0.094005,-0.129853,-0.566849,0.340469,-0.759090,0.597599,0.195879,...,-0.521937,-0.219749,-0.386088,-0.908459,-0.557653,-0.534421,-1.098041,0.137910,-0.087929,0.598431
75%,-0.333368,0.633240,-0.133214,1.222072,0.748684,0.023421,1.859747,-0.106580,2.475773,1.160842,...,-0.045596,1.162439,1.052936,-0.484653,-0.140518,0.128204,-0.840207,0.869358,0.432992,1.206221
max,1.024299,3.331015,1.587369,4.251413,4.727424,3.115454,4.993408,2.785006,5.268154,4.820943,...,4.401333,4.692024,4.748040,4.231028,6.460195,2.873626,0.950643,3.461173,3.068672,4.143774

In [16]:
synthetic_data.to_csv(SYN_DATA_HOME + SYNTHETIC_FILE, index = False)