In [1]:
#Load libraries
import warnings
warnings.filterwarnings("ignore")
import numpy as np
import pandas as pd
from copulas.multivariate import GaussianMultivariate
from matplotlib import pyplot as plt
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [2]:
import sys
sys.path.append('../../../PREPROCESSING')
from gaussian_multivariate import DataPreProcessor

In [3]:
FUNCTIONS_HOME = '../../../functions/evaluation_functions/' #home directory of the project
REAL_DATA_HOME = '../../../data/raw/rembrandt/' #home directory of the project
SYN_DATA_HOME  = '../../../data/processed/rembrandt/' #home directory of the project
TRAIN_FILE = '0_Depression_Data_Real_Train.csv'
SYNTHETIC_FILE = '0_Depression_Data_Synthetic_GM.csv'

## 1. Read data

In [4]:
real_data = pd.read_csv(REAL_DATA_HOME + TRAIN_FILE)
categorical_columns = ['group']
for col in categorical_columns :
    real_data[col] = real_data[col].astype('category')
data_train = real_data
real_data

,group,ma1,hars1,ma2,hars2,ma3,hars3,ma4,hars4,ma5,...,ma10,hars10,ma11,hars11,ma12,hars12,ma13,hars13,ma14,hars14
0,Control,-0.872369,-0.943320,-0.872369,-0.943320,-0.872369,-1.130271,-0.872369,-0.943320,-0.872369,...,-0.872369,-0.943320,-0.872369,-1.130271,-0.872369,-1.130271,-0.497156,-0.756370,-0.872369,-0.943320
1,Remitted,0.628481,0.926183,-0.309550,-0.569420,0.816087,-0.569420,0.816087,-0.382469,2.504542,...,2.316936,1.487034,2.879754,0.926183,2.316936,0.926183,1.378905,0.552282,1.003693,-0.008569
2,Remitted,-0.121944,-0.195519,-0.872369,-0.756370,-0.497156,-0.008569,-0.121944,-0.008569,-0.497156,...,-0.497156,-0.756370,0.440874,-0.195519,-0.497156,-0.195519,0.253268,-0.756370,0.816087,0.739233
3,Remitted,0.816087,0.739233,-0.309550,-0.569420,-0.121944,0.739233,-0.684762,-0.569420,-0.684762,...,-0.497156,-0.756370,-0.684762,-0.943320,-0.684762,-0.756370,-0.497156,-0.943320,-0.497156,0.178382
4,Remitted,1.003693,2.047885,0.253268,2.234835,0.628481,1.487034,1.003693,2.234835,1.754117,...,2.129330,3.543488,1.191299,0.739233,1.754117,1.860935,0.816087,0.739233,-0.497156,1.673984
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,Control,-0.872369,-0.382469,-0.309550,0.178382,-0.684762,-0.756370,-0.872369,-1.130271,-0.121944,...,-0.684762,-0.382469,-0.872369,-0.756370,-0.684762,-0.943320,-0.872369,-0.943320,-0.309550,0.926183
92,Control,-0.872369,-0.569420,-0.684762,-0.195519,-0.872369,-0.756370,-0.872369,-0.569420,-0.872369,...,-0.872369,-0.008569,-0.872369,-0.008569,-0.872369,-0.008569,-0.872369,-0.569420,-0.684762,0.178382
93,Control,-0.684762,-0.943320,-0.684762,-0.756370,-0.497156,-0.943320,-0.121944,-0.756370,-0.872369,...,-0.497156,-0.943320,-0.684762,-0.943320,-0.872369,-0.943320,-0.872369,-0.943320,-0.872369,-0.569420
94,Control,-0.684762,-0.756370,-0.872369,-0.756370,-0.872369,-0.943320,-0.872369,-0.008569,-0.497156,...,-0.684762,0.365332,-0.684762,-1.130271,-0.684762,-1.130271,-0.872369,-0.943320,-0.309550,0.365332
95,Remitted,-0.684762,-0.569420,-0.309550,-0.756370,-0.121944,-0.008569,-0.309550,-0.008569,-0.121944,...,-0.309550,-0.569420,-0.872369,-0.943320,0.628481,0.552282,-0.497156,-0.569420,-0.497156,0.178382

In [5]:
data_train.dtypes

group     category
ma1        float64
hars1      float64
ma2        float64
hars2      float64
ma3        float64
hars3      float64
ma4        float64
hars4      float64
ma5        float64
hars5      float64
ma6        float64
hars6      float64
ma7        float64
hars7      float64
ma8        float64
hars8      float64
ma9        float64
hars9      float64
ma10       float64
hars10     float64
ma11       float64
hars11     float64
ma12       float64
hars12     float64
ma13       float64
hars13     float64
ma14       float64
hars14     float64
dtype: object

In [6]:
# data configuration
preprocessor = DataPreProcessor(data_train)
data_train = preprocessor.preprocess_train_data()
data_train

,ma1,hars1,ma2,hars2,ma3,hars3,ma4,hars4,ma5,hars5,...,ma11,hars11,ma12,hars12,ma13,hars13,ma14,hars14,group0,group1
0,-0.872369,-0.943320,-0.872369,-0.943320,-0.872369,-1.130271,-0.872369,-0.943320,-0.872369,-1.130271,...,-0.872369,-1.130271,-0.872369,-1.130271,-0.497156,-0.756370,-0.872369,-0.943320,0.730957,0.500000
1,0.628481,0.926183,-0.309550,-0.569420,0.816087,-0.569420,0.816087,-0.382469,2.504542,0.178382,...,2.879754,0.926183,2.316936,0.926183,1.378905,0.552282,1.003693,-0.008569,0.500000,0.730957
2,-0.121944,-0.195519,-0.872369,-0.756370,-0.497156,-0.008569,-0.121944,-0.008569,-0.497156,-0.195519,...,0.440874,-0.195519,-0.497156,-0.195519,0.253268,-0.756370,0.816087,0.739233,0.500000,0.730957
3,0.816087,0.739233,-0.309550,-0.569420,-0.121944,0.739233,-0.684762,-0.569420,-0.684762,-0.382469,...,-0.684762,-0.943320,-0.684762,-0.756370,-0.497156,-0.943320,-0.497156,0.178382,0.500000,0.730957
4,1.003693,2.047885,0.253268,2.234835,0.628481,1.487034,1.003693,2.234835,1.754117,1.860935,...,1.191299,0.739233,1.754117,1.860935,0.816087,0.739233,-0.497156,1.673984,0.500000,0.730957
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,-0.872369,-0.382469,-0.309550,0.178382,-0.684762,-0.756370,-0.872369,-1.130271,-0.121944,-0.195519,...,-0.872369,-0.756370,-0.684762,-0.943320,-0.872369,-0.943320,-0.309550,0.926183,0.730957,0.500000
92,-0.872369,-0.569420,-0.684762,-0.195519,-0.872369,-0.756370,-0.872369,-0.569420,-0.872369,-0.756370,...,-0.872369,-0.008569,-0.872369,-0.008569,-0.872369,-0.569420,-0.684762,0.178382,0.730957,0.500000
93,-0.684762,-0.943320,-0.684762,-0.756370,-0.497156,-0.943320,-0.121944,-0.756370,-0.872369,-1.130271,...,-0.684762,-0.943320,-0.872369,-0.943320,-0.872369,-0.943320,-0.872369,-0.569420,0.730957,0.500000
94,-0.684762,-0.756370,-0.872369,-0.756370,-0.872369,-0.943320,-0.872369,-0.008569,-0.497156,-0.008569,...,-0.684762,-1.130271,-0.684762,-1.130271,-0.872369,-0.943320,-0.309550,0.365332,0.730957,0.500000
95,-0.684762,-0.569420,-0.309550,-0.756370,-0.121944,-0.008569,-0.309550,-0.008569,-0.121944,0.178382,...,-0.872369,-0.943320,0.628481,0.552282,-0.497156,-0.569420,-0.497156,0.178382,0.500000,0.730957

## 2. Train the model and generate data

In [7]:
gm = GaussianMultivariate()
gm.fit(data_train)

In [8]:
generated_samples = gm.sample(len(data_train))
generated_samples

,ma1,hars1,ma2,hars2,ma3,hars3,ma4,hars4,ma5,hars5,...,ma11,hars11,ma12,hars12,ma13,hars13,ma14,hars14,group0,group1
0,0.205875,1.666929,0.027499,0.812336,2.143901,2.371067,0.325139,0.358222,2.339175,3.186686,...,0.415031,0.656864,-0.791394,-0.833291,0.087396,1.589851,0.135561,0.575611,0.543827,0.687168
1,-0.711492,-0.695166,-0.978856,-0.986423,-1.238163,-1.360812,-0.675340,-0.683794,-0.467972,-0.588478,...,-0.806604,-1.751534,-0.805991,-1.660750,-0.827117,-0.732491,-0.695939,-1.860239,0.723147,0.507778
2,-0.666669,0.144931,-0.815925,-0.781343,1.773360,1.463537,0.634446,0.529802,1.524290,1.842922,...,2.051664,3.407842,1.522785,3.122808,3.237207,2.391341,0.026513,0.639414,0.734851,0.496114
3,-0.789575,-0.225257,-0.168826,0.342664,-1.051718,-0.438112,0.013381,1.647405,-1.105866,-0.696920,...,-0.864295,-0.150831,-0.247579,-0.146039,-0.481964,-0.535933,-0.355955,0.011270,0.529466,0.701473
4,-0.523823,-0.156905,-0.353042,-0.526743,-0.534734,0.484559,-0.007897,0.006802,-0.306415,0.096575,...,0.473707,0.792979,-0.467661,-0.177332,-0.097979,-0.397791,-0.717832,-0.030366,0.693181,0.537746
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,0.072537,1.320036,-0.360072,-0.445960,0.994687,1.414214,-0.083550,0.772456,0.001498,0.306495,...,-0.068896,1.539587,-0.755726,-0.345174,0.073679,0.566898,-0.074234,0.957388,0.544002,0.686966
92,-0.843856,-0.867316,-0.590182,-0.869050,0.214753,-0.093671,-0.028980,-0.725966,-0.825706,-0.549589,...,-0.847669,-1.583679,-0.745442,-1.054146,-0.581273,-1.136829,-0.749949,-0.585377,0.500817,0.730150
93,0.246558,1.115083,1.275956,11.950878,0.691709,1.287503,-1.103111,-0.796453,-0.456246,-0.426804,...,-0.871645,-1.245003,-0.871462,-1.298774,-1.553615,-1.465718,-1.347361,-0.290510,0.547087,0.683877
94,-0.800517,-0.021533,-0.223322,-0.738683,0.573506,1.289456,0.702364,1.180324,-0.326154,1.203185,...,-0.108082,0.093772,0.266940,-0.022149,1.088528,0.187968,0.610327,1.213997,0.482116,0.748856
95,-1.427242,-0.475675,-1.276583,-1.071552,-1.194664,-0.650174,-0.949322,-0.842159,-1.028060,-0.854808,...,-0.748411,-0.577158,-0.693602,-0.671331,-0.971480,-1.060722,-0.783056,-0.792272,0.785982,0.444974

## 3. Transform Generated Data

In [9]:
synthetic_data = preprocessor.transform_data(generated_samples)
synthetic_data

,group,ma1,hars1,ma2,hars2,ma3,hars3,ma4,hars4,ma5,...,ma10,hars10,ma11,hars11,ma12,hars12,ma13,hars13,ma14,hars14
0,Remitted,0.205875,1.666929,0.027499,0.812336,2.143901,2.371067,0.325139,0.358222,2.339175,...,-0.266378,2.205005,0.415031,0.656864,-0.791394,-0.833291,0.087396,1.589851,0.135561,0.575611
1,Control,-0.711492,-0.695166,-0.978856,-0.986423,-1.238163,-1.360812,-0.675340,-0.683794,-0.467972,...,-0.597241,-1.046943,-0.806604,-1.751534,-0.805991,-1.660750,-0.827117,-0.732491,-0.695939,-1.860239
2,Control,-0.666669,0.144931,-0.815925,-0.781343,1.773360,1.463537,0.634446,0.529802,1.524290,...,0.033502,2.652962,2.051664,3.407842,1.522785,3.122808,3.237207,2.391341,0.026513,0.639414
3,Remitted,-0.789575,-0.225257,-0.168826,0.342664,-1.051718,-0.438112,0.013381,1.647405,-1.105866,...,-0.501686,0.213281,-0.864295,-0.150831,-0.247579,-0.146039,-0.481964,-0.535933,-0.355955,0.011270
4,Control,-0.523823,-0.156905,-0.353042,-0.526743,-0.534734,0.484559,-0.007897,0.006802,-0.306415,...,-0.637426,0.132826,0.473707,0.792979,-0.467661,-0.177332,-0.097979,-0.397791,-0.717832,-0.030366
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,Remitted,0.072537,1.320036,-0.360072,-0.445960,0.994687,1.414214,-0.083550,0.772456,0.001498,...,-0.416074,0.838366,-0.068896,1.539587,-0.755726,-0.345174,0.073679,0.566898,-0.074234,0.957388
92,Remitted,-0.843856,-0.867316,-0.590182,-0.869050,0.214753,-0.093671,-0.028980,-0.725966,-0.825706,...,-0.771105,-1.081811,-0.847669,-1.583679,-0.745442,-1.054146,-0.581273,-1.136829,-0.749949,-0.585377
93,Remitted,0.246558,1.115083,1.275956,11.950878,0.691709,1.287503,-1.103111,-0.796453,-0.456246,...,-0.739724,-0.892254,-0.871645,-1.245003,-0.871462,-1.298774,-1.553615,-1.465718,-1.347361,-0.290510
94,Remitted,-0.800517,-0.021533,-0.223322,-0.738683,0.573506,1.289456,0.702364,1.180324,-0.326154,...,1.455113,1.256310,-0.108082,0.093772,0.266940,-0.022149,1.088528,0.187968,0.610327,1.213997
95,Control,-1.427242,-0.475675,-1.276583,-1.071552,-1.194664,-0.650174,-0.949322,-0.842159,-1.028060,...,-0.634676,-0.947780,-0.748411,-0.577158,-0.693602,-0.671331,-0.971480,-1.060722,-0.783056,-0.792272

In [10]:
real_data.describe()

,ma1,hars1,ma2,hars2,ma3,hars3,ma4,hars4,ma5,hars5,...,ma10,hars10,ma11,hars11,ma12,hars12,ma13,hars13,ma14,hars14
count,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,...,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000
mean,-0.139532,-0.092307,-0.270466,-0.236414,0.102793,0.098538,0.110609,0.110223,0.188779,0.172540,...,0.053937,0.125802,-0.071134,-0.168255,-0.037912,-0.164361,-0.235289,-0.366890,-0.008599,0.345858
std,0.603834,0.845636,0.514261,0.832629,0.983578,1.014129,0.945601,0.996333,1.158028,1.165597,...,1.162812,1.101414,1.170961,1.025757,1.116340,1.071261,0.774467,0.719553,0.736712,0.722519
min,-0.872369,-1.130271,-0.872369,-1.130271,-0.872369,-1.130271,-0.872369,-1.130271,-0.872369,-1.130271,...,-0.872369,-1.130271,-0.872369,-1.130271,-0.872369,-1.130271,-0.872369,-1.130271,-0.872369,-1.130271
25%,-0.684762,-0.756370,-0.684762,-0.756370,-0.684762,-0.756370,-0.684762,-0.569420,-0.684762,-0.756370,...,-0.544058,-0.569420,-0.684762,-0.943320,-0.684762,-0.943320,-0.872369,-0.943320,-0.497156,-0.008569
50%,-0.309550,-0.382469,-0.309550,-0.569420,-0.121944,-0.195519,-0.121944,-0.195519,-0.215747,-0.008569,...,-0.497156,-0.195519,-0.684762,-0.569420,-0.497156,-0.569420,-0.497156,-0.569420,-0.121944,0.365332
75%,0.300170,0.552282,-0.121944,0.178382,0.628481,0.739233,0.487776,0.552282,0.628481,0.739233,...,0.300170,0.552282,0.253268,0.552282,0.253268,0.412070,0.065662,-0.195519,0.253268,0.739233
max,1.378905,2.047885,1.003693,3.543488,3.817785,3.356537,3.254966,2.982637,4.943422,3.917388,...,4.192997,4.104339,4.568209,3.356537,4.568209,4.291289,3.254966,2.234835,2.879754,2.982637

In [11]:
synthetic_data.describe()

,ma1,hars1,ma2,hars2,ma3,hars3,ma4,hars4,ma5,hars5,...,ma10,hars10,ma11,hars11,ma12,hars12,ma13,hars13,ma14,hars14
count,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,...,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000
mean,-0.225850,-0.155043,-0.258704,-0.218576,0.269695,0.321408,0.073879,0.118472,0.412497,0.374821,...,1.362811,0.071064,-0.146578,-0.172780,-0.189362,-0.184459,-0.081844,-0.204811,-0.057565,0.341592
std,0.607042,0.839806,0.594282,1.527584,1.141583,1.220351,1.025123,1.013635,1.496462,1.417997,...,14.789619,0.928365,1.015554,1.137954,0.680685,1.100604,0.955853,0.934148,0.834563,0.757647
min,-1.427242,-1.898003,-1.276583,-1.141289,-1.503817,-1.609693,-1.717536,-1.132474,-2.050958,-1.799860,...,-0.860387,-1.103471,-0.872280,-1.751534,-0.871462,-1.753168,-1.553615,-1.712671,-1.361540,-1.860239
25%,-0.674045,-0.778438,-0.600959,-0.788520,-0.556095,-0.654206,-0.667968,-0.695037,-0.556977,-0.700612,...,-0.740147,-0.594645,-0.839122,-1.007747,-0.748921,-1.031049,-0.720685,-0.854604,-0.658905,-0.044717
50%,-0.349240,-0.338210,-0.363103,-0.622294,0.065402,0.144030,-0.103021,-0.181169,-0.201646,-0.034981,...,-0.510217,-0.086140,-0.575186,-0.405244,-0.419143,-0.418952,-0.315149,-0.394046,-0.182368,0.369908
75%,0.173911,0.169285,-0.001437,-0.284458,0.872031,1.287991,0.572176,0.682323,1.170503,1.053548,...,-0.137177,0.476630,0.067090,0.474492,0.111902,0.566070,0.405057,0.136415,0.124462,0.709864
max,1.601595,1.974963,1.275956,11.950878,4.229051,2.890471,3.267259,3.207192,5.918032,3.910856,...,143.968874,2.652962,4.794259,3.407842,1.522785,3.963972,3.268532,2.391341,3.029461,3.105246

In [12]:
synthetic_data.to_csv(SYN_DATA_HOME + SYNTHETIC_FILE, index = False)