In [1]:
#Load libraries
import warnings
warnings.filterwarnings("ignore")
import numpy as np
import pandas as pd
from ctgan import CTGAN

In [2]:
FUNCTIONS_HOME = '../../../functions/evaluation_functions/' #home directory of the project
REAL_DATA_HOME = '../../../data/raw/chap/' #home directory of the project
SYN_DATA_HOME  = '../../../data/processed/chap/' #home directory of the project
TRAIN_FILE = '1_Chap_Data_Real_Train.csv'
SYNTHETIC_FILE = '1_Chap_Data_Synthetic_CTGAN.csv'

## 1. Load the dataset

In [3]:
real_data = pd.read_csv(REAL_DATA_HOME + TRAIN_FILE)
real_data

,group,sbp1,sbp2,sbp3,sbp4,dbp1,dbp2,dbp3,dbp4
0,Group0,2.009493,0.084640,-0.020160,0.107037,0.857051,-0.048580,0.141517,0.137274
1,Group0,1.647881,0.285048,0.750705,-0.365256,0.594206,-0.094862,0.201428,-0.240859
2,Group0,0.045838,-0.301003,-0.007641,0.189160,1.875668,-0.152879,0.003445,0.012916
3,Group0,-1.626382,0.438629,-0.352224,-0.147169,-2.445341,0.362086,-0.132354,-0.016382
4,Group0,-0.244556,-0.781058,0.191160,0.637441,-2.766078,-1.110363,0.746589,0.140332
...,...,...,...,...,...,...,...,...,...
2712,Group0,0.048656,0.340805,0.146978,-0.077990,1.468295,-0.105885,0.037067,-0.001841
2713,Group0,-3.007362,-0.110868,-0.547719,-0.061449,-3.286850,-0.079093,-0.126217,0.165070
2714,Group0,0.481546,-0.118290,-0.159216,-0.046665,0.013795,0.235801,-0.128855,0.206748
2715,Group0,0.199530,0.371273,0.268324,0.670192,0.275167,-0.382674,0.076358,0.294886
2716,Group0,3.319253,0.852148,-1.115749,-0.142213,4.733011,1.221218,-0.466025,-0.221787

In [4]:
real_data.dtypes

group     object
sbp1     float64
sbp2     float64
sbp3     float64
sbp4     float64
dbp1     float64
dbp2     float64
dbp3     float64
dbp4     float64
dtype: object

In [5]:
discrete_columns = ['group']
discrete_columns

['group']

In [6]:
ctgan = CTGAN()
ctgan.fit(real_data, discrete_columns)

In [7]:
synthetic_data = ctgan.sample(len(real_data))
synthetic_data

,group,sbp1,sbp2,sbp3,sbp4,dbp1,dbp2,dbp3,dbp4
0,Group0,6.094322,-0.208446,0.416890,0.515579,-7.706072,-0.527509,0.166410,0.211860
1,Group0,2.291828,-0.762772,-0.112074,0.083636,0.846565,1.539027,-0.004124,0.277265
2,Group0,-5.112419,-0.377207,0.224469,0.505163,7.457264,-0.497955,-0.752442,0.063517
3,Group0,6.007161,-0.165590,-0.152581,0.389270,-4.636239,-0.214006,-0.530647,0.046882
4,Group0,1.082027,-1.209130,-0.070217,0.204933,1.570072,0.721873,0.099834,0.010630
...,...,...,...,...,...,...,...,...,...
2712,Group0,3.814451,0.190931,-0.282501,0.325604,-2.521737,-0.304934,-0.905134,-0.061680
2713,Group0,-1.059330,0.216962,-0.006728,0.091072,-5.399747,1.604053,-1.166298,-0.027417
2714,Group0,9.769922,0.944167,0.407352,0.002913,-4.778331,0.129506,0.001454,0.194900
2715,Group0,-4.384517,0.040398,-0.064242,0.055481,-5.280489,-0.847199,0.277913,0.162433
2716,Group1,-7.699921,-0.086799,-0.938739,0.373963,-10.346422,0.302718,-0.679478,0.292614

In [8]:
real_data.describe()

,sbp1,sbp2,sbp3,sbp4,dbp1,dbp2,dbp3,dbp4
count,2717.000000,2717.000000,2717.000000,2717.000000,2717.000000,2717.000000,2717.000000,2717.000000
mean,0.072962,-0.015681,0.030675,0.038696,0.057982,-0.056777,0.022021,0.028471
std,4.086347,0.729714,0.509026,0.262684,3.710970,0.733119,0.371803,0.180631
min,-18.884976,-2.732794,-2.023219,-1.289887,-17.202625,-2.580206,-1.409579,-0.862115
25%,-2.674316,-0.470025,-0.306902,-0.126936,-2.352459,-0.519699,-0.224223,-0.085791
50%,0.301318,-0.016234,0.026003,0.034561,0.244464,-0.044513,0.016090,0.032382
75%,2.979693,0.441029,0.354509,0.202381,2.653050,0.436457,0.258646,0.144028
max,11.023203,3.680704,2.233565,1.292367,12.307994,2.916243,1.550258,0.852724

In [9]:
synthetic_data.describe()

,sbp1,sbp2,sbp3,sbp4,dbp1,dbp2,dbp3,dbp4
count,2717.000000,2717.000000,2717.000000,2717.000000,2717.000000,2717.000000,2717.000000,2717.000000
mean,-1.371769,0.130057,-0.074911,0.119158,-2.110746,0.147513,-0.123970,0.113958
std,5.707076,0.859753,0.550428,0.300558,5.370844,0.753192,0.419339,0.186546
min,-19.020211,-2.930564,-2.104990,-1.182085,-16.098477,-3.103835,-1.863827,-0.559512
25%,-5.711706,-0.377207,-0.462343,-0.070714,-5.979946,-0.321638,-0.394900,-0.011631
50%,-1.125531,0.150461,-0.093989,0.106821,-1.594227,0.164807,-0.124128,0.106878
75%,3.132534,0.673142,0.296612,0.301963,1.900483,0.646848,0.144575,0.233370
max,11.987062,3.592086,1.735822,1.532252,12.190999,2.916772,1.326742,1.090253

In [10]:
synthetic_data.to_csv(SYN_DATA_HOME + SYNTHETIC_FILE, index = False)