In [1]:
#Load libraries
import warnings
warnings.filterwarnings("ignore")
import numpy as np
import pandas as pd
from copulas.multivariate import GaussianMultivariate
from matplotlib import pyplot as plt
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [2]:
import sys
sys.path.append('../../../PREPROCESSING')
from gaussian_multivariate import DataPreProcessor

In [3]:
FUNCTIONS_HOME = '../../../functions/evaluation_functions/' #home directory of the project
REAL_DATA_HOME = '../../../data/raw/chap/' #home directory of the project
SYN_DATA_HOME  = '../../../data/processed/chap/' #home directory of the project
TRAIN_FILE = '1_Chap_Data_Real_Train.csv'
SYNTHETIC_FILE = '1_Chap_Data_Synthetic_GM.csv'

## 1. Read data

In [4]:
real_data = pd.read_csv(REAL_DATA_HOME + TRAIN_FILE)
categorical_columns = ['group']
for col in categorical_columns :
    real_data[col] = real_data[col].astype('category')
data_train = real_data
real_data

,group,sbp1,sbp2,sbp3,sbp4,dbp1,dbp2,dbp3,dbp4
0,Group0,2.009493,0.084640,-0.020160,0.107037,0.857051,-0.048580,0.141517,0.137274
1,Group0,1.647881,0.285048,0.750705,-0.365256,0.594206,-0.094862,0.201428,-0.240859
2,Group0,0.045838,-0.301003,-0.007641,0.189160,1.875668,-0.152879,0.003445,0.012916
3,Group0,-1.626382,0.438629,-0.352224,-0.147169,-2.445341,0.362086,-0.132354,-0.016382
4,Group0,-0.244556,-0.781058,0.191160,0.637441,-2.766078,-1.110363,0.746589,0.140332
...,...,...,...,...,...,...,...,...,...
2712,Group0,0.048656,0.340805,0.146978,-0.077990,1.468295,-0.105885,0.037067,-0.001841
2713,Group0,-3.007362,-0.110868,-0.547719,-0.061449,-3.286850,-0.079093,-0.126217,0.165070
2714,Group0,0.481546,-0.118290,-0.159216,-0.046665,0.013795,0.235801,-0.128855,0.206748
2715,Group0,0.199530,0.371273,0.268324,0.670192,0.275167,-0.382674,0.076358,0.294886
2716,Group0,3.319253,0.852148,-1.115749,-0.142213,4.733011,1.221218,-0.466025,-0.221787

In [5]:
data_train.dtypes

group    category
sbp1      float64
sbp2      float64
sbp3      float64
sbp4      float64
dbp1      float64
dbp2      float64
dbp3      float64
dbp4      float64
dtype: object

In [6]:
# data configuration
preprocessor = DataPreProcessor(data_train)
data_train = preprocessor.preprocess_train_data()
data_train

,sbp1,sbp2,sbp3,sbp4,dbp1,dbp2,dbp3,dbp4,group0,group1
0,2.009493,0.084640,-0.020160,0.107037,0.857051,-0.048580,0.141517,0.137274,0.730957,0.5
1,1.647881,0.285048,0.750705,-0.365256,0.594206,-0.094862,0.201428,-0.240859,0.730957,0.5
2,0.045838,-0.301003,-0.007641,0.189160,1.875668,-0.152879,0.003445,0.012916,0.730957,0.5
3,-1.626382,0.438629,-0.352224,-0.147169,-2.445341,0.362086,-0.132354,-0.016382,0.730957,0.5
4,-0.244556,-0.781058,0.191160,0.637441,-2.766078,-1.110363,0.746589,0.140332,0.730957,0.5
...,...,...,...,...,...,...,...,...,...,...
2712,0.048656,0.340805,0.146978,-0.077990,1.468295,-0.105885,0.037067,-0.001841,0.730957,0.5
2713,-3.007362,-0.110868,-0.547719,-0.061449,-3.286850,-0.079093,-0.126217,0.165070,0.730957,0.5
2714,0.481546,-0.118290,-0.159216,-0.046665,0.013795,0.235801,-0.128855,0.206748,0.730957,0.5
2715,0.199530,0.371273,0.268324,0.670192,0.275167,-0.382674,0.076358,0.294886,0.730957,0.5
2716,3.319253,0.852148,-1.115749,-0.142213,4.733011,1.221218,-0.466025,-0.221787,0.730957,0.5

## 2. Train the model and generate data

In [7]:
gm = GaussianMultivariate()
gm.fit(data_train)

In [8]:
generated_samples = gm.sample(len(data_train))
generated_samples

,sbp1,sbp2,sbp3,sbp4,dbp1,dbp2,dbp3,dbp4,group0,group1
0,2.380848,1.437030,-0.272048,0.040346,2.832409,0.493765,0.076030,0.063044,0.732548,0.498403
1,1.298324,-0.872445,-0.199532,0.152709,-2.241116,-0.446154,0.230793,0.003883,0.734098,0.496854
2,-1.418017,-0.705664,0.241301,-0.045601,-4.902270,-1.270940,-0.013372,-0.047719,0.734177,0.496785
3,-4.099877,-0.001948,0.106520,0.082828,-5.664343,-0.253154,-0.025399,0.262347,0.494640,0.736313
4,0.913321,0.179957,-0.291470,0.143974,-3.917341,-0.663543,0.021135,0.134408,0.737346,0.493609
...,...,...,...,...,...,...,...,...,...,...
2712,-6.513359,-1.122108,0.402461,-0.092153,-3.640159,-0.628105,0.345454,-0.211614,0.727968,0.502996
2713,5.728211,0.579826,0.396367,-0.133686,8.010616,0.676937,0.013272,-0.012647,0.718994,0.511972
2714,-1.149620,-0.016340,-0.443537,-0.220429,-1.130278,-0.292354,-0.017134,-0.058395,0.736727,0.494224
2715,6.866358,1.290890,-0.499429,0.124473,6.232146,0.600912,0.018399,0.237372,0.742107,0.488851
2716,0.410120,1.331399,0.151248,-0.293815,-0.419693,0.262700,0.438740,-0.186146,0.731251,0.499705

## 3. Transform Generated Data

In [9]:
synthetic_data = preprocessor.transform_data(generated_samples)
synthetic_data

,group,sbp1,sbp2,sbp3,sbp4,dbp1,dbp2,dbp3,dbp4
0,Group0,2.380848,1.437030,-0.272048,0.040346,2.832409,0.493765,0.076030,0.063044
1,Group0,1.298324,-0.872445,-0.199532,0.152709,-2.241116,-0.446154,0.230793,0.003883
2,Group0,-1.418017,-0.705664,0.241301,-0.045601,-4.902270,-1.270940,-0.013372,-0.047719
3,Group1,-4.099877,-0.001948,0.106520,0.082828,-5.664343,-0.253154,-0.025399,0.262347
4,Group0,0.913321,0.179957,-0.291470,0.143974,-3.917341,-0.663543,0.021135,0.134408
...,...,...,...,...,...,...,...,...,...
2712,Group0,-6.513359,-1.122108,0.402461,-0.092153,-3.640159,-0.628105,0.345454,-0.211614
2713,Group0,5.728211,0.579826,0.396367,-0.133686,8.010616,0.676937,0.013272,-0.012647
2714,Group0,-1.149620,-0.016340,-0.443537,-0.220429,-1.130278,-0.292354,-0.017134,-0.058395
2715,Group0,6.866358,1.290890,-0.499429,0.124473,6.232146,0.600912,0.018399,0.237372
2716,Group0,0.410120,1.331399,0.151248,-0.293815,-0.419693,0.262700,0.438740,-0.186146

In [10]:
real_data.describe()

,sbp1,sbp2,sbp3,sbp4,dbp1,dbp2,dbp3,dbp4
count,2717.000000,2717.000000,2717.000000,2717.000000,2717.000000,2717.000000,2717.000000,2717.000000
mean,0.072962,-0.015681,0.030675,0.038696,0.057982,-0.056777,0.022021,0.028471
std,4.086347,0.729714,0.509026,0.262684,3.710970,0.733119,0.371803,0.180631
min,-18.884976,-2.732794,-2.023219,-1.289887,-17.202625,-2.580206,-1.409579,-0.862115
25%,-2.674316,-0.470025,-0.306902,-0.126936,-2.352459,-0.519699,-0.224223,-0.085791
50%,0.301318,-0.016234,0.026003,0.034561,0.244464,-0.044513,0.016090,0.032382
75%,2.979693,0.441029,0.354509,0.202381,2.653050,0.436457,0.258646,0.144028
max,11.023203,3.680704,2.233565,1.292367,12.307994,2.916243,1.550258,0.852724

In [11]:
synthetic_data.describe()

,sbp1,sbp2,sbp3,sbp4,dbp1,dbp2,dbp3,dbp4
count,2717.000000,2717.000000,2717.000000,2717.000000,2717.000000,2717.000000,2717.000000,2717.000000
mean,0.027925,0.017343,0.003999,0.044100,0.018915,-0.027439,0.000598,0.031616
std,4.076231,0.737218,0.513399,0.268018,3.767992,0.737832,0.373283,0.183245
min,-16.815502,-2.811968,-2.115352,-1.108937,-16.292440,-3.155124,-1.523916,-0.782748
25%,-2.649370,-0.439601,-0.338173,-0.124180,-2.464123,-0.504376,-0.240048,-0.086393
50%,0.254880,0.022085,0.016328,0.036324,0.170063,-0.043970,0.001812,0.031183
75%,2.977858,0.496252,0.344877,0.209174,2.557357,0.463613,0.246191,0.148258
max,10.719722,2.599828,2.244338,1.282805,11.913798,2.534496,1.435460,0.788194

In [12]:
synthetic_data.to_csv(SYN_DATA_HOME + SYNTHETIC_FILE, index = False)