# TRTR Dataset 0 - REMBRANDT

In [25]:
#import libraries
import warnings
warnings.filterwarnings("ignore")
import numpy as np
import pandas as pd
import os
print('Libraries imported!!')

Libraries imported!!

In [26]:
#define directory of functions and actual directory
FUNCTIONS_HOME = '../../../functions/evaluation_functions/' #home directory of the project
REAL_DATA_HOME = '../../../data/raw/rembrandt/' #home directory of the project
SYN_DATA_HOME  = '../../../data/processed/rembrandt/' #home directory of the project
FUNCTIONS_DIR = 'EVALUATION FUNCTIONS/UTILITY'
ACTUAL_DIR = os.getcwd()

#change directory to functions directory
os.chdir(FUNCTIONS_HOME + FUNCTIONS_DIR)
#import functions for data labelling analisys
from utility_evaluation import DataPreProcessor
from utility_evaluation import train_evaluate_model

#change directory to actual directory
os.chdir(ACTUAL_DIR)
print('Functions imported!!')

Functions imported!!

## 1. Read data

In [27]:
#read real dataset
train_data = pd.read_csv(REAL_DATA_HOME + '0_Depression_Data_Real_Train.csv')
categorical_columns = ['group']
for col in categorical_columns :
    train_data[col] = train_data[col].astype('category')
train_data

,group,ma1,hars1,ma2,hars2,ma3,hars3,ma4,hars4,ma5,...,ma10,hars10,ma11,hars11,ma12,hars12,ma13,hars13,ma14,hars14
0,Control,-0.872369,-0.943320,-0.872369,-0.943320,-0.872369,-1.130271,-0.872369,-0.943320,-0.872369,...,-0.872369,-0.943320,-0.872369,-1.130271,-0.872369,-1.130271,-0.497156,-0.756370,-0.872369,-0.943320
1,Remitted,0.628481,0.926183,-0.309550,-0.569420,0.816087,-0.569420,0.816087,-0.382469,2.504542,...,2.316936,1.487034,2.879754,0.926183,2.316936,0.926183,1.378905,0.552282,1.003693,-0.008569
2,Remitted,-0.121944,-0.195519,-0.872369,-0.756370,-0.497156,-0.008569,-0.121944,-0.008569,-0.497156,...,-0.497156,-0.756370,0.440874,-0.195519,-0.497156,-0.195519,0.253268,-0.756370,0.816087,0.739233
3,Remitted,0.816087,0.739233,-0.309550,-0.569420,-0.121944,0.739233,-0.684762,-0.569420,-0.684762,...,-0.497156,-0.756370,-0.684762,-0.943320,-0.684762,-0.756370,-0.497156,-0.943320,-0.497156,0.178382
4,Remitted,1.003693,2.047885,0.253268,2.234835,0.628481,1.487034,1.003693,2.234835,1.754117,...,2.129330,3.543488,1.191299,0.739233,1.754117,1.860935,0.816087,0.739233,-0.497156,1.673984
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,Control,-0.872369,-0.382469,-0.309550,0.178382,-0.684762,-0.756370,-0.872369,-1.130271,-0.121944,...,-0.684762,-0.382469,-0.872369,-0.756370,-0.684762,-0.943320,-0.872369,-0.943320,-0.309550,0.926183
92,Control,-0.872369,-0.569420,-0.684762,-0.195519,-0.872369,-0.756370,-0.872369,-0.569420,-0.872369,...,-0.872369,-0.008569,-0.872369,-0.008569,-0.872369,-0.008569,-0.872369,-0.569420,-0.684762,0.178382
93,Control,-0.684762,-0.943320,-0.684762,-0.756370,-0.497156,-0.943320,-0.121944,-0.756370,-0.872369,...,-0.497156,-0.943320,-0.684762,-0.943320,-0.872369,-0.943320,-0.872369,-0.943320,-0.872369,-0.569420
94,Control,-0.684762,-0.756370,-0.872369,-0.756370,-0.872369,-0.943320,-0.872369,-0.008569,-0.497156,...,-0.684762,0.365332,-0.684762,-1.130271,-0.684762,-1.130271,-0.872369,-0.943320,-0.309550,0.365332
95,Remitted,-0.684762,-0.569420,-0.309550,-0.756370,-0.121944,-0.008569,-0.309550,-0.008569,-0.121944,...,-0.309550,-0.569420,-0.872369,-0.943320,0.628481,0.552282,-0.497156,-0.569420,-0.497156,0.178382

In [28]:
#read test data
test_data = pd.read_csv(REAL_DATA_HOME + '0_Depression_Data_Real_Test.csv')
for col in categorical_columns :
    test_data[col] = test_data[col].astype('category')
test_data

,group,ma1,hars1,ma2,hars2,ma3,hars3,ma4,hars4,ma5,...,ma10,hars10,ma11,hars11,ma12,hars12,ma13,hars13,ma14,hars14
0,Remitted,-0.309550,-0.569420,-0.872369,-0.756370,-0.497156,-0.008569,-0.684762,0.178382,-0.121944,...,0.065662,-0.008569,1.566511,-0.008569,0.440874,-0.569420,-0.309550,0.178382,-0.121944,0.178382
1,Remitted,0.065662,0.178382,-0.309550,-0.569420,-0.497156,-0.382469,0.253268,-0.195519,-0.497156,...,-0.497156,-0.382469,-0.497156,-0.756370,-0.684762,-0.382469,-0.872369,-0.195519,-0.309550,0.739233
2,Remitted,-0.684762,-0.943320,-0.309550,-0.569420,-0.497156,-0.943320,-0.121944,-0.756370,-0.497156,...,-0.872369,-0.382469,-0.309550,-0.195519,-0.121944,-0.382469,-0.309550,-0.569420,-0.497156,-0.382469
3,Remitted,0.440874,-0.195519,1.003693,0.552282,0.440874,-0.569420,0.440874,-0.569420,-0.121944,...,0.440874,0.365332,-0.684762,-0.756370,0.065662,-0.008569,-0.497156,-0.195519,-0.121944,-0.008569
4,Remitted,1.003693,0.365332,-0.309550,-0.756370,2.879754,2.982637,0.816087,-0.195519,0.065662,...,-0.497156,-0.569420,-0.684762,-0.569420,0.065662,-0.943320,-0.309550,-0.569420,0.628481,0.365332
5,Remitted,0.440874,0.178382,-0.309550,-0.569420,0.628481,-0.382469,1.191299,0.739233,0.065662,...,-0.872369,-0.195519,-0.684762,-0.195519,-0.121944,0.552282,-0.872369,-0.382469,-0.497156,-0.382469
6,Remitted,-0.684762,0.365332,0.816087,0.739233,-0.309550,0.365332,0.816087,1.300084,0.253268,...,-0.309550,0.178382,-0.121944,0.739233,0.065662,-0.008569,-0.121944,-0.569420,-0.309550,1.113133
7,Remitted,-0.309550,-0.569420,-0.121944,-0.569420,-0.872369,-0.756370,-0.684762,-0.569420,-0.872369,...,-0.497156,-0.569420,-0.872369,-1.130271,-0.497156,-0.569420,-0.872369,-0.756370,0.065662,-0.008569
8,Remitted,0.628481,-0.382469,-0.309550,-0.569420,-0.497156,-0.569420,0.816087,-0.943320,1.941724,...,3.817785,1.860935,-0.872369,-0.569420,-0.684762,-1.130271,-0.309550,-1.130271,0.440874,0.552282
9,Control,-0.872369,-1.130271,-0.872369,-0.569420,-0.684762,-0.943320,-0.497156,-0.756370,-0.872369,...,-0.872369,-1.130271,-0.872369,-1.130271,-0.872369,-1.130271,-0.872369,-0.943320,-0.684762,0.178382
10,Remitted,-0.309550,-0.382469,0.065662,0.365332,2.129330,0.926183,3.817785,0.739233,4.005391,...,3.067360,1.860935,3.254966,2.234835,0.628481,0.178382,0.253268,0.552282,0.065662,1.113133
11,Control,-0.309550,-0.382469,-0.309550,0.739233,-0.121944,0.739233,0.253268,0.739233,-0.121944,...,0.065662,0.739233,-0.684762,0.178382,1.003693,1.860935,-0.872369,-0.943320,-0.121944,1.113133
12,Control,-0.684762,-0.943320,-0.872369,-0.943320,-0.872369,-1.130271,-0.497156,-0.569420,-0.872369,...,-0.684762,-1.130271,-0.872369,-0.943320,-0.872369,-0.943320,-0.872369,-0.943320,-0.872369,-0.569420
13,Control,-0.872369,-1.130271,-0.872369,-0.756370,-0.684762,-0.943320,-0.684762,-0.569420,-0.872369,...,-0.872369,-1.130271,-0.684762,-0.382469,-0.497156,-0.382469,-0.872369,-0.569420,-0.872369,-1.130271
14,Control,-0.872369,-0.943320,-0.872369,0.178382,-0.872369,-1.130271,-0.497156,-0.756370,-0.121944,...,-0.309550,-0.569420,-0.121944,-0.008569,-0.497156,-0.195519,-0.684762,-0.382469,-0.872369,-1.130271
15,Control,-0.872369,-0.569420,-0.872369,-0.569420,-0.309550,-0.943320,-0.684762,-0.943320,-0.684762,...,-0.497156,-0.756370,-0.684762,-0.943320,-0.684762,-1.130271,-0.872369,-0.943320,-0.684762,0.365332
16,Remitted,-0.497156,-0.943320,0.440874,1.113133,0.816087,0.365332,2.879754,1.300084,1.003693,...,-0.497156,-0.569420,-0.684762,-0.756370,-0.684762,-1.130271,-0.309550,-0.756370,-0.309550,0.926183
17,Remitted,-0.309550,-0.382469,-0.309550,-0.569420,-0.497156,-0.382469,-0.684762,-0.943320,1.191299,...,-0.497156,-0.569420,-0.684762,-1.130271,-0.684762,-1.130271,-0.684762,-0.943320,0.065662,0.552282
18,Remitted,-0.309550,-0.382469,0.253268,-0.195519,-0.497156,-0.943320,0.253268,-0.008569,-0.121944,...,-0.684762,-0.756370,-0.684762,-0.943320,-0.497156,-0.569420,-0.309550,-0.569420,-0.497156,-0.569420
19,Control,-0.684762,-0.943320,-0.684762,-0.569420,-0.121944,-0.569420,-0.497156,-0.382469,-0.497156,...,-0.497156,-0.382469,-0.684762,-0.756370,-0.872369,-0.756370,-0.497156,-0.756370,-0.684762,-0.382469
20,Control,0.253268,0.178382,0.253268,1.113133,-0.309550,-0.756370,-0.121944,-0.008569,-0.121944,...,-0.309550,0.552282,-0.121944,0.178382,-0.309550,0.739233,-0.121944,0.739233,0.065662,0.365332
21,Remitted,-0.121944,0.178382,-0.121944,-0.008569,1.003693,0.178382,3.254966,1.860935,1.003693,...,0.628481,-0.382469,0.628481,1.860935,2.129330,1.487034,4.005391,2.982637,2.504542,2.047885
22,Control,-0.684762,-0.943320,-0.872369,-0.756370,-0.872369,-1.130271,-0.872369,-1.130271,-0.872369,...,-0.684762,-0.756370,-0.684762,-0.943320,-0.684762,-0.943320,-0.872369,-1.130271,-0.497156,0.365332
23,Remitted,0.253268,-0.008569,1.003693,3.543488,3.254966,3.917388,2.504542,5.039090,1.003693,...,-0.497156,-0.569420,-0.684762,-0.943320,0.065662,-0.195519,0.816087,0.365332,-0.121944,1.300084

In [29]:
target = 'group'
#quick look at the breakdown of class values
print('Train data')
print(train_data.shape)
print(train_data.groupby(target).size())
print('#####################################')
print('Test data')
print(test_data.shape)
print(test_data.groupby(target).size())

Train data
(96, 29)
group
Control     31
Remitted    65
dtype: int64
#####################################
Test data
(24, 29)
group
Control      9
Remitted    15
dtype: int64

## 2. Pre-process training data

In [30]:
target = 'group'

# 先分离特征和目标
X = train_data.drop(columns=[target])
y = train_data[target]

# 然后基于 X 定义列
categorical_columns = X.select_dtypes(include=['object', 'category']).columns.tolist()
numerical_columns = X.select_dtypes(include=['int64', 'float64']).columns.tolist()

# categories 需要根据你的实际分类列调整
categories = [np.array(range(2))] if categorical_columns else []

data_preprocessor = DataPreProcessor(categorical_columns, numerical_columns, categories)
x_train = data_preprocessor.preprocess_train_data(X)
y_train = y

x_train.shape, y_train.shape

((96, 28), (96,))

## 3. Preprocess test data

In [31]:
x_test = data_preprocessor.preprocess_test_data(test_data.loc[:, test_data.columns != target])
y_test = test_data.loc[:, target]
x_test.shape, y_test.shape

((24, 28), (24,))

## 4. Create a dataset to save the results

In [32]:
results = pd.DataFrame(columns = ['model','accuracy','precision','recall','f1'])
results

Empty DataFrame
Columns: [model, accuracy, precision, recall, f1]
Index: []

## 4. Train and evaluate Random Forest Classifier

In [33]:
rf_results = train_evaluate_model('RF', x_train, y_train, x_test, y_test)
results = pd.concat([results, rf_results], ignore_index=True)
rf_results

[Parallel(n_jobs=3)]: Using backend ThreadingBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done  44 tasks      | elapsed:    0.0s
[Parallel(n_jobs=3)]: Done 100 out of 100 | elapsed:    0.1s finished
[Parallel(n_jobs=3)]: Using backend ThreadingBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done  44 tasks      | elapsed:    0.0s
[Parallel(n_jobs=3)]: Done 100 out of 100 | elapsed:    0.0s finished

  model  accuracy  precision  recall      f1
0    RF    0.8333     0.8333  0.8333  0.8333

## 5. Train and Evaluate KNeighbors Classifier

In [34]:
knn_results = train_evaluate_model('KNN', x_train, y_train, x_test, y_test)
results = pd.concat([results, knn_results], ignore_index=True)
knn_results

  model  accuracy  precision  recall      f1
0   KNN    0.7917     0.7982  0.7917  0.7936

## 6. Train and evaluate Decision Tree Classifier

In [35]:
dt_results = train_evaluate_model('DT', x_train, y_train, x_test, y_test)
results = pd.concat([results, dt_results], ignore_index=True)
dt_results

  model  accuracy  precision  recall      f1
0    DT    0.9167     0.9167  0.9167  0.9167

## 7. Train and evaluate Support Vector Machines Classifier

In [36]:
svm_results = train_evaluate_model('SVM', x_train, y_train, x_test, y_test)
results = pd.concat([results, svm_results], ignore_index=True)
svm_results

[LibSVM]...WARN: libsvm Solver reached max_iter
optimization finished, #iter = 300
obj = -6.076040, rho = -2.134398
nSV = 20, nBSV = 0
Total nSV = 20
.*
optimization finished, #iter = 149
obj = -5.166165, rho = -2.415716
nSV = 15, nBSV = 0
Total nSV = 15
...WARN: libsvm Solver reached max_iter
optimization finished, #iter = 300
obj = -5.389054, rho = -1.976517
nSV = 21, nBSV = 0
Total nSV = 21
...WARN: libsvm Solver reached max_iter
optimization finished, #iter = 300
obj = -4.736673, rho = -1.841582
nSV = 20, nBSV = 0
Total nSV = 20
...WARN: libsvm Solver reached max_iter
optimization finished, #iter = 300
obj = -3.079447, rho = -1.542717
nSV = 16, nBSV = 0
Total nSV = 16
..*
optimization finished, #iter = 262
obj = -6.883515, rho = 2.291844
nSV = 19, nBSV = 0
Total nSV = 19

  model  accuracy  precision  recall      f1
0   SVM    0.9583     0.9609  0.9583  0.9578

## 8. Train and evaluate Multilayer Perceptron Classifier

In [37]:
mlp_results = train_evaluate_model('MLP', x_train, y_train, x_test, y_test)
results = pd.concat([results, mlp_results], ignore_index=True)
mlp_results

Iteration 1, loss = 0.65372249
Iteration 2, loss = 0.61056067
Iteration 3, loss = 0.57298350
Iteration 4, loss = 0.54103265
Iteration 5, loss = 0.51330711
Iteration 6, loss = 0.48882980
Iteration 7, loss = 0.46624977
Iteration 8, loss = 0.44516984
Iteration 9, loss = 0.42561671
Iteration 10, loss = 0.40736607
Iteration 11, loss = 0.39046545
Iteration 12, loss = 0.37455728
Iteration 13, loss = 0.35957412
Iteration 14, loss = 0.34503842
Iteration 15, loss = 0.33078450
Iteration 16, loss = 0.31684698
Iteration 17, loss = 0.30315878
Iteration 18, loss = 0.28979367
Iteration 19, loss = 0.27682716
Iteration 20, loss = 0.26429908
Iteration 21, loss = 0.25209125
Iteration 22, loss = 0.23996236
Iteration 23, loss = 0.22797184
Iteration 24, loss = 0.21615468
Iteration 25, loss = 0.20442430
Iteration 26, loss = 0.19295115
Iteration 27, loss = 0.18163475
Iteration 28, loss = 0.17066138
Iteration 29, loss = 0.16004484
Iteration 30, loss = 0.14988890
Iteration 31, loss = 0.14038934
Iteration 32, loss = 0.13135333
Iteration 33, loss = 0.12286070
Iteration 34, loss = 0.11485497
Iteration 35, loss = 0.10734185
Iteration 36, loss = 0.10024392
Iteration 37, loss = 0.09359512
Iteration 38, loss = 0.08721676
Iteration 39, loss = 0.08107683
Iteration 40, loss = 0.07523536
Iteration 41, loss = 0.06976208
Iteration 42, loss = 0.06457550
Iteration 43, loss = 0.05971018
Iteration 44, loss = 0.05517213
Iteration 45, loss = 0.05092004
Iteration 46, loss = 0.04697017
Iteration 47, loss = 0.04331808
Iteration 48, loss = 0.03991037
Iteration 49, loss = 0.03673430
Iteration 50, loss = 0.03376085
Iteration 51, loss = 0.03095299
Iteration 52, loss = 0.02831674
Iteration 53, loss = 0.02588169
Iteration 54, loss = 0.02359948
Iteration 55, loss = 0.02149029
Iteration 56, loss = 0.01955863
Iteration 57, loss = 0.01779626
Iteration 58, loss = 0.01621211
Iteration 59, loss = 0.01480784
Iteration 60, loss = 0.01357465
Iteration 61, loss = 0.01247859
Iteration 62, loss = 0.01149964
Iteration 63, loss = 0.01062482
Iteration 64, loss = 0.00983288
Iteration 65, loss = 0.00911729
Iteration 66, loss = 0.00847165
Iteration 67, loss = 0.00788641
Iteration 68, loss = 0.00735622
Iteration 69, loss = 0.00687358
Iteration 70, loss = 0.00643024
Iteration 71, loss = 0.00602569
Iteration 72, loss = 0.00565542
Iteration 73, loss = 0.00531613
Iteration 74, loss = 0.00500725
Iteration 75, loss = 0.00472463
Iteration 76, loss = 0.00446573
Iteration 77, loss = 0.00422845
Iteration 78, loss = 0.00401306
Iteration 79, loss = 0.00381608
Iteration 80, loss = 0.00363510
Iteration 81, loss = 0.00346798
Iteration 82, loss = 0.00331372
Iteration 83, loss = 0.00317149
Iteration 84, loss = 0.00304030
Iteration 85, loss = 0.00291850
Iteration 86, loss = 0.00280529
Iteration 87, loss = 0.00269956
Iteration 88, loss = 0.00260066
Iteration 89, loss = 0.00250779
Iteration 90, loss = 0.00242135
Iteration 91, loss = 0.00234032
Iteration 92, loss = 0.00226424
Iteration 93, loss = 0.00219344
Iteration 94, loss = 0.00212692
Iteration 95, loss = 0.00206378
Iteration 96, loss = 0.00200410
Iteration 97, loss = 0.00194788
Iteration 98, loss = 0.00189468
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.

  model  accuracy  precision  recall      f1
0   MLP     0.875      0.875   0.875  0.8733

## 9. Save results file

In [38]:
results.to_csv('RESULTS/models_results_real.csv', index=False)
results

  model  accuracy  precision  recall      f1
0    RF    0.8333     0.8333  0.8333  0.8333
1   KNN    0.7917     0.7982  0.7917  0.7936
2    DT    0.9167     0.9167  0.9167  0.9167
3   SVM    0.9583     0.9609  0.9583  0.9578
4   MLP    0.8750     0.8750  0.8750  0.8733