# TSTR CTGAN Dataset 0 - REMBRANDT

In [18]:
#import libraries
import warnings
warnings.filterwarnings("ignore")
import numpy as np
import pandas as pd
import os
print('Libraries imported!!')
# os.makedirs('RESULTS', exist_ok=True)

Libraries imported!!

In [19]:
#define directory of functions and actual directory
FUNCTIONS_HOME = '../../../functions/evaluation_functions/' #home directory of the project
REAL_DATA_HOME = '../../../data/raw/rembrandt/' #home directory of the project
SYN_DATA_HOME  = '../../../data/processed/rembrandt/' #home directory of the project
FUNCTIONS_DIR = 'EVALUATION FUNCTIONS/UTILITY'
ACTUAL_DIR = os.getcwd()

#change directory to functions directory
os.chdir(FUNCTIONS_HOME + FUNCTIONS_DIR)

#import functions for data labelling analisys
from utility_evaluation import DataPreProcessor
from utility_evaluation import train_evaluate_model

#change directory to actual directory
os.chdir(ACTUAL_DIR)
print('Functions imported!!')

Functions imported!!

## 1. Read data

In [20]:
#read real dataset
train_data = pd.read_csv(SYN_DATA_HOME + '0_Depression_Data_Synthetic_CTGAN.csv')
categorical_columns = ['group']
for col in categorical_columns :
    train_data[col] = train_data[col].astype('category')
train_data

,group,ma1,hars1,ma2,hars2,ma3,hars3,ma4,hars4,ma5,...,ma10,hars10,ma11,hars11,ma12,hars12,ma13,hars13,ma14,hars14
0,Control,-1.003556,-0.226949,-0.360741,1.665643,-0.374173,-0.719837,0.117326,-0.059717,-1.060621,...,1.997617,2.209913,-0.805324,-1.343262,-1.210574,-0.859809,-1.474385,-0.257095,-0.645991,1.065644
1,Remitted,-0.527101,-0.209512,-0.755790,0.517736,0.427923,-0.264881,1.132112,-2.300370,4.194925,...,-0.855932,1.849551,2.977862,-0.740115,-0.387391,0.117365,-0.928756,1.768706,-0.526334,-1.453899
2,Control,-0.706105,-1.456352,-0.033474,3.599761,2.625076,-0.445736,2.877741,-1.133792,2.610473,...,-0.567815,1.155937,-1.018540,4.231028,-0.746965,-0.838060,-1.064316,1.336957,-0.862144,-1.000972
3,Control,-1.147055,0.339980,0.068270,-0.434389,1.362031,0.769278,1.005867,-1.062024,2.442056,...,-0.494691,-1.840407,-0.478278,-0.620337,0.467659,-1.537834,-0.651787,0.282659,0.371402,0.513703
4,Control,-0.058185,-0.736248,1.374066,0.088680,0.535779,0.252779,2.635707,-1.226003,-0.546500,...,-0.813242,-0.490979,-0.340536,-0.563108,-0.831039,-1.090361,0.337101,1.441900,0.230506,0.416467
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,Control,-1.268920,1.441439,-0.408406,-0.002770,-1.242248,-1.253781,-0.430132,-0.807286,3.074015,...,2.308607,-1.260471,1.039893,-1.914381,-1.068055,-0.770923,0.053616,-0.215893,0.484578,1.196593
92,Remitted,-0.785475,-0.020996,-0.637153,-0.491999,-1.147190,0.525333,4.593586,1.055464,3.412927,...,-0.249155,4.238194,2.395894,-0.844417,-1.002109,0.707884,-1.050444,0.304690,0.016266,2.738263
93,Control,0.203743,-0.691457,-0.349035,0.064769,2.319464,-1.106602,1.233028,-0.404369,0.794581,...,-0.323307,-1.148934,-0.297931,-0.755385,-0.724639,-0.422440,-0.892635,-0.243411,0.727578,0.991291
94,Remitted,-0.474835,-0.425688,-0.143483,0.513089,0.617330,1.602350,-0.641298,0.271874,0.064736,...,1.166148,2.566697,-0.556327,-1.385773,-0.428820,-0.678955,-0.985812,-0.494861,-1.001289,-1.666044
95,Remitted,0.211628,-0.908148,-0.764098,2.192874,-0.087136,-1.155783,1.883427,-0.525599,2.177610,...,-0.715902,-0.551522,4.030542,-1.493387,-0.714806,1.201556,-1.331778,0.146733,-1.140095,1.318775

In [21]:
#read test data
test_data = pd.read_csv(REAL_DATA_HOME + '0_Depression_Data_Real_Test.csv')
for col in categorical_columns :
    test_data[col] = test_data[col].astype('category')
test_data

,group,ma1,hars1,ma2,hars2,ma3,hars3,ma4,hars4,ma5,...,ma10,hars10,ma11,hars11,ma12,hars12,ma13,hars13,ma14,hars14
0,Remitted,-0.309550,-0.569420,-0.872369,-0.756370,-0.497156,-0.008569,-0.684762,0.178382,-0.121944,...,0.065662,-0.008569,1.566511,-0.008569,0.440874,-0.569420,-0.309550,0.178382,-0.121944,0.178382
1,Remitted,0.065662,0.178382,-0.309550,-0.569420,-0.497156,-0.382469,0.253268,-0.195519,-0.497156,...,-0.497156,-0.382469,-0.497156,-0.756370,-0.684762,-0.382469,-0.872369,-0.195519,-0.309550,0.739233
2,Remitted,-0.684762,-0.943320,-0.309550,-0.569420,-0.497156,-0.943320,-0.121944,-0.756370,-0.497156,...,-0.872369,-0.382469,-0.309550,-0.195519,-0.121944,-0.382469,-0.309550,-0.569420,-0.497156,-0.382469
3,Remitted,0.440874,-0.195519,1.003693,0.552282,0.440874,-0.569420,0.440874,-0.569420,-0.121944,...,0.440874,0.365332,-0.684762,-0.756370,0.065662,-0.008569,-0.497156,-0.195519,-0.121944,-0.008569
4,Remitted,1.003693,0.365332,-0.309550,-0.756370,2.879754,2.982637,0.816087,-0.195519,0.065662,...,-0.497156,-0.569420,-0.684762,-0.569420,0.065662,-0.943320,-0.309550,-0.569420,0.628481,0.365332
5,Remitted,0.440874,0.178382,-0.309550,-0.569420,0.628481,-0.382469,1.191299,0.739233,0.065662,...,-0.872369,-0.195519,-0.684762,-0.195519,-0.121944,0.552282,-0.872369,-0.382469,-0.497156,-0.382469
6,Remitted,-0.684762,0.365332,0.816087,0.739233,-0.309550,0.365332,0.816087,1.300084,0.253268,...,-0.309550,0.178382,-0.121944,0.739233,0.065662,-0.008569,-0.121944,-0.569420,-0.309550,1.113133
7,Remitted,-0.309550,-0.569420,-0.121944,-0.569420,-0.872369,-0.756370,-0.684762,-0.569420,-0.872369,...,-0.497156,-0.569420,-0.872369,-1.130271,-0.497156,-0.569420,-0.872369,-0.756370,0.065662,-0.008569
8,Remitted,0.628481,-0.382469,-0.309550,-0.569420,-0.497156,-0.569420,0.816087,-0.943320,1.941724,...,3.817785,1.860935,-0.872369,-0.569420,-0.684762,-1.130271,-0.309550,-1.130271,0.440874,0.552282
9,Control,-0.872369,-1.130271,-0.872369,-0.569420,-0.684762,-0.943320,-0.497156,-0.756370,-0.872369,...,-0.872369,-1.130271,-0.872369,-1.130271,-0.872369,-1.130271,-0.872369,-0.943320,-0.684762,0.178382
10,Remitted,-0.309550,-0.382469,0.065662,0.365332,2.129330,0.926183,3.817785,0.739233,4.005391,...,3.067360,1.860935,3.254966,2.234835,0.628481,0.178382,0.253268,0.552282,0.065662,1.113133
11,Control,-0.309550,-0.382469,-0.309550,0.739233,-0.121944,0.739233,0.253268,0.739233,-0.121944,...,0.065662,0.739233,-0.684762,0.178382,1.003693,1.860935,-0.872369,-0.943320,-0.121944,1.113133
12,Control,-0.684762,-0.943320,-0.872369,-0.943320,-0.872369,-1.130271,-0.497156,-0.569420,-0.872369,...,-0.684762,-1.130271,-0.872369,-0.943320,-0.872369,-0.943320,-0.872369,-0.943320,-0.872369,-0.569420
13,Control,-0.872369,-1.130271,-0.872369,-0.756370,-0.684762,-0.943320,-0.684762,-0.569420,-0.872369,...,-0.872369,-1.130271,-0.684762,-0.382469,-0.497156,-0.382469,-0.872369,-0.569420,-0.872369,-1.130271
14,Control,-0.872369,-0.943320,-0.872369,0.178382,-0.872369,-1.130271,-0.497156,-0.756370,-0.121944,...,-0.309550,-0.569420,-0.121944,-0.008569,-0.497156,-0.195519,-0.684762,-0.382469,-0.872369,-1.130271
15,Control,-0.872369,-0.569420,-0.872369,-0.569420,-0.309550,-0.943320,-0.684762,-0.943320,-0.684762,...,-0.497156,-0.756370,-0.684762,-0.943320,-0.684762,-1.130271,-0.872369,-0.943320,-0.684762,0.365332
16,Remitted,-0.497156,-0.943320,0.440874,1.113133,0.816087,0.365332,2.879754,1.300084,1.003693,...,-0.497156,-0.569420,-0.684762,-0.756370,-0.684762,-1.130271,-0.309550,-0.756370,-0.309550,0.926183
17,Remitted,-0.309550,-0.382469,-0.309550,-0.569420,-0.497156,-0.382469,-0.684762,-0.943320,1.191299,...,-0.497156,-0.569420,-0.684762,-1.130271,-0.684762,-1.130271,-0.684762,-0.943320,0.065662,0.552282
18,Remitted,-0.309550,-0.382469,0.253268,-0.195519,-0.497156,-0.943320,0.253268,-0.008569,-0.121944,...,-0.684762,-0.756370,-0.684762,-0.943320,-0.497156,-0.569420,-0.309550,-0.569420,-0.497156,-0.569420
19,Control,-0.684762,-0.943320,-0.684762,-0.569420,-0.121944,-0.569420,-0.497156,-0.382469,-0.497156,...,-0.497156,-0.382469,-0.684762,-0.756370,-0.872369,-0.756370,-0.497156,-0.756370,-0.684762,-0.382469
20,Control,0.253268,0.178382,0.253268,1.113133,-0.309550,-0.756370,-0.121944,-0.008569,-0.121944,...,-0.309550,0.552282,-0.121944,0.178382,-0.309550,0.739233,-0.121944,0.739233,0.065662,0.365332
21,Remitted,-0.121944,0.178382,-0.121944,-0.008569,1.003693,0.178382,3.254966,1.860935,1.003693,...,0.628481,-0.382469,0.628481,1.860935,2.129330,1.487034,4.005391,2.982637,2.504542,2.047885
22,Control,-0.684762,-0.943320,-0.872369,-0.756370,-0.872369,-1.130271,-0.872369,-1.130271,-0.872369,...,-0.684762,-0.756370,-0.684762,-0.943320,-0.684762,-0.943320,-0.872369,-1.130271,-0.497156,0.365332
23,Remitted,0.253268,-0.008569,1.003693,3.543488,3.254966,3.917388,2.504542,5.039090,1.003693,...,-0.497156,-0.569420,-0.684762,-0.943320,0.065662,-0.195519,0.816087,0.365332,-0.121944,1.300084

In [22]:
target = 'group'
#quick look at the breakdown of class values
print('Train data')
print(train_data.shape)
# print(train_data.groupby(target).size())
print('#####################################')
print('Test data')
print(test_data.shape)
print(test_data.groupby(target).size())

Train data
(96, 29)
#####################################
Test data
(24, 29)
group
Control      9
Remitted    15
dtype: int64

## 2. Pre-process training data

In [23]:
target = 'group'
categorical_columns = []
numerical_columns = train_data.select_dtypes(include=['int64','float64']).columns.tolist()
categories = [np.array(range(2))] if categorical_columns else []
data_preprocessor = DataPreProcessor(categorical_columns, numerical_columns, categories)
x_train = data_preprocessor.preprocess_train_data(train_data.loc[:, train_data.columns != target])
y_train = train_data.loc[:, target]

x_train.shape, y_train.shape

((96, 28), (96,))

## 3. Preprocess test data

In [24]:
x_test = data_preprocessor.preprocess_test_data(test_data.loc[:, test_data.columns != target])
y_test = test_data.loc[:, target]
x_test.shape, y_test.shape

((24, 28), (24,))

## 4. Create a dataset to save the results

In [25]:
results = pd.DataFrame(columns = ['model','accuracy','precision','recall','f1'])
results

Empty DataFrame
Columns: [model, accuracy, precision, recall, f1]
Index: []

## 4. Train and evaluate Random Forest Classifier

In [26]:
rf_results = train_evaluate_model('RF', x_train, y_train, x_test, y_test)
results = pd.concat([results, rf_results], ignore_index=True)
rf_results

[Parallel(n_jobs=3)]: Using backend ThreadingBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done  44 tasks      | elapsed:    0.0s
[Parallel(n_jobs=3)]: Done 100 out of 100 | elapsed:    0.1s finished
[Parallel(n_jobs=3)]: Using backend ThreadingBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done  44 tasks      | elapsed:    0.0s
[Parallel(n_jobs=3)]: Done 100 out of 100 | elapsed:    0.0s finished

  model  accuracy  precision  recall      f1
0    RF      0.75     0.7675    0.75  0.7536

## 5. Train and Evaluate KNeighbors Classifier

In [27]:
knn_results = train_evaluate_model('KNN', x_train, y_train, x_test, y_test)
results = pd.concat([results, knn_results], ignore_index=True)
knn_results

  model  accuracy  precision  recall      f1
0   KNN     0.625     0.7344   0.625  0.6204

## 6. Train and evaluate Decision Tree Classifier

In [28]:
dt_results = train_evaluate_model('DT', x_train, y_train, x_test, y_test)
results = pd.concat([results, dt_results], ignore_index=True)
dt_results

  model  accuracy  precision  recall      f1
0    DT     0.875      0.875   0.875  0.8733

## 7. Train and evaluate Support Vector Machines Classifier

In [29]:
svm_results = train_evaluate_model('SVM', x_train, y_train, x_test, y_test)
results = pd.concat([results, svm_results], ignore_index=True)
svm_results

[LibSVM]...WARN: libsvm Solver reached max_iter
optimization finished, #iter = 300
obj = -41.030103, rho = 0.285386
nSV = 35, nBSV = 0
Total nSV = 35
...WARN: libsvm Solver reached max_iter
optimization finished, #iter = 300
obj = -16.202006, rho = -0.333167
nSV = 30, nBSV = 0
Total nSV = 30
...WARN: libsvm Solver reached max_iter
optimization finished, #iter = 300
obj = -18.344219, rho = 0.461530
nSV = 31, nBSV = 0
Total nSV = 31
...WARN: libsvm Solver reached max_iter
optimization finished, #iter = 300
obj = -32.594198, rho = -0.435041
nSV = 34, nBSV = 0
Total nSV = 34
...WARN: libsvm Solver reached max_iter
optimization finished, #iter = 300
obj = -9.495705, rho = -1.028780
nSV = 31, nBSV = 0
Total nSV = 31
...WARN: libsvm Solver reached max_iter
optimization finished, #iter = 300
obj = -45.687436, rho = 0.233530
nSV = 41, nBSV = 0
Total nSV = 41

  model  accuracy  precision  recall      f1
0   SVM      0.75     0.8214    0.75  0.7083

## 8. Train and evaluate Multilayer Perceptron Classifier

In [30]:
mlp_results = train_evaluate_model('MLP', x_train, y_train, x_test, y_test)
results =pd.concat([results, mlp_results], ignore_index=True)
mlp_results

Iteration 1, loss = 0.72319854
Iteration 2, loss = 0.69821289
Iteration 3, loss = 0.67570105
Iteration 4, loss = 0.65497208
Iteration 5, loss = 0.63529191
Iteration 6, loss = 0.61658212
Iteration 7, loss = 0.59868179
Iteration 8, loss = 0.58114509
Iteration 9, loss = 0.56373071
Iteration 10, loss = 0.54628811
Iteration 11, loss = 0.52894716
Iteration 12, loss = 0.51139882
Iteration 13, loss = 0.49363461
Iteration 14, loss = 0.47558150
Iteration 15, loss = 0.45737996
Iteration 16, loss = 0.43886784
Iteration 17, loss = 0.42037639
Iteration 18, loss = 0.40190581
Iteration 19, loss = 0.38349786
Iteration 20, loss = 0.36521518
Iteration 21, loss = 0.34718656
Iteration 22, loss = 0.32937082
Iteration 23, loss = 0.31168779
Iteration 24, loss = 0.29428258
Iteration 25, loss = 0.27718676
Iteration 26, loss = 0.26037038
Iteration 27, loss = 0.24402921
Iteration 28, loss = 0.22835214
Iteration 29, loss = 0.21328200
Iteration 30, loss = 0.19879798
Iteration 31, loss = 0.18487975
Iteration 32, loss = 0.17148951
Iteration 33, loss = 0.15866296
Iteration 34, loss = 0.14643368
Iteration 35, loss = 0.13485630
Iteration 36, loss = 0.12396239
Iteration 37, loss = 0.11368670
Iteration 38, loss = 0.10389056
Iteration 39, loss = 0.09464435
Iteration 40, loss = 0.08604219
Iteration 41, loss = 0.07804395
Iteration 42, loss = 0.07063258
Iteration 43, loss = 0.06378986
Iteration 44, loss = 0.05750488
Iteration 45, loss = 0.05178309
Iteration 46, loss = 0.04655894
Iteration 47, loss = 0.04180717
Iteration 48, loss = 0.03747148
Iteration 49, loss = 0.03358338
Iteration 50, loss = 0.03011526
Iteration 51, loss = 0.02702579
Iteration 52, loss = 0.02426491
Iteration 53, loss = 0.02186162
Iteration 54, loss = 0.01971746
Iteration 55, loss = 0.01779970
Iteration 56, loss = 0.01608656
Iteration 57, loss = 0.01455968
Iteration 58, loss = 0.01320443
Iteration 59, loss = 0.01199722
Iteration 60, loss = 0.01093262
Iteration 61, loss = 0.00998997
Iteration 62, loss = 0.00915639
Iteration 63, loss = 0.00841643
Iteration 64, loss = 0.00775581
Iteration 65, loss = 0.00716989
Iteration 66, loss = 0.00664481
Iteration 67, loss = 0.00617237
Iteration 68, loss = 0.00574809
Iteration 69, loss = 0.00536603
Iteration 70, loss = 0.00502648
Iteration 71, loss = 0.00471878
Iteration 72, loss = 0.00443952
Iteration 73, loss = 0.00418561
Iteration 74, loss = 0.00395455
Iteration 75, loss = 0.00374435
Iteration 76, loss = 0.00355138
Iteration 77, loss = 0.00337490
Iteration 78, loss = 0.00321333
Iteration 79, loss = 0.00306514
Iteration 80, loss = 0.00292838
Iteration 81, loss = 0.00280198
Iteration 82, loss = 0.00268386
Iteration 83, loss = 0.00257419
Iteration 84, loss = 0.00247247
Iteration 85, loss = 0.00237791
Iteration 86, loss = 0.00228983
Iteration 87, loss = 0.00220800
Iteration 88, loss = 0.00213160
Iteration 89, loss = 0.00206012
Iteration 90, loss = 0.00199351
Iteration 91, loss = 0.00193104
Iteration 92, loss = 0.00187266
Iteration 93, loss = 0.00181773
Iteration 94, loss = 0.00176593
Iteration 95, loss = 0.00171713
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.

  model  accuracy  precision  recall      f1
0   MLP    0.6667     0.7133  0.6667  0.6713

## 9. Save results file

In [31]:
results.to_csv('RESULTS/models_results_ctgan.csv', index=False)
results

  model  accuracy  precision  recall      f1
0    RF    0.7500     0.7675  0.7500  0.7536
1   KNN    0.6250     0.7344  0.6250  0.6204
2    DT    0.8750     0.8750  0.8750  0.8733
3   SVM    0.7500     0.8214  0.7500  0.7083
4   MLP    0.6667     0.7133  0.6667  0.6713