# TSTR ECDF Dataset 0 - REMBRANDT

In [3]:
#import libraries
import warnings
warnings.filterwarnings("ignore")
import numpy as np
import pandas as pd
import os
print('Libraries imported!!')

Libraries imported!!

In [2]:
#define directory of functions and actual directory
FUNCTIONS_HOME = '../../../functions/evaluation_functions/' #home directory of the project
REAL_DATA_HOME = '../../../data/raw/rembrandt/' #home directory of the project
SYN_DATA_HOME  = '../../../data/processed/rembrandt/' #home directory of the project
FUNCTIONS_DIR = 'EVALUATION FUNCTIONS/UTILITY'
ACTUAL_DIR = os.getcwd()

#change directory to functions directory
os.chdir(FUNCTIONS_HOME + FUNCTIONS_DIR)
#import functions for data labelling analisys
from utility_evaluation import DataPreProcessor
from utility_evaluation import train_evaluate_model

#change directory to actual directory
os.chdir(ACTUAL_DIR)
print('Functions imported!!')

Functions imported!!

## 1. Read data

In [5]:
#read real dataset
train_data = pd.read_csv(SYN_DATA_HOME + '0_Depression_Data_Synthetic_ECDF.csv')
categorical_columns = ['group']
for col in categorical_columns :
    train_data[col] = train_data[col].astype('category')
train_data

,group,ma1,hars1,ma2,hars2,ma3,hars3,ma4,hars4,ma5,...,ma10,hars10,ma11,hars11,ma12,hars12,ma13,hars13,ma14,hars14
0,Control,-0.894716,-1.086952,-0.518559,-0.551602,-0.706638,-0.730052,-0.706638,-0.730052,-0.142402,...,-0.706638,-0.551602,-0.330481,-0.551602,-0.330481,-0.373152,-0.894716,-1.086952,-0.894716,-0.908502
1,Control,-0.706638,-0.908502,-0.330481,-0.551602,-0.518559,0.697549,-0.894716,-0.373152,-0.142402,...,-0.894716,-0.730052,-0.706638,-0.730052,0.233755,-0.373152,-0.894716,-0.551602,-0.894716,-0.908502
2,Remitted,-0.706638,-0.730052,-0.142402,-0.730052,-0.142402,-0.016252,-0.142402,1.054449,0.045676,...,-0.142402,0.697549,-0.518559,0.519099,-0.518559,-0.730052,0.986068,1.946699,0.045676,0.697549
3,Remitted,-0.518559,-0.016252,0.233755,-0.730052,0.421833,0.697549,0.421833,1.232899,2.866853,...,2.866853,0.519099,3.431088,2.660500,1.174147,1.946699,0.421833,0.162198,-0.330481,1.589799
4,Remitted,0.609911,-0.016252,-0.330481,-0.908502,-0.518559,-0.908502,-0.330481,-0.373152,-0.518559,...,-0.518559,-0.551602,-0.518559,-0.373152,0.609911,-0.194702,-0.706638,-0.373152,2.114539,-0.551602
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,Remitted,-0.518559,-0.908502,-0.330481,0.697549,0.045676,-0.551602,-0.142402,-0.373152,-0.142402,...,-0.518559,1.054449,-0.142402,-0.194702,-0.142402,-0.194702,-0.894716,-0.730052,-0.706638,-0.016252
116,Remitted,-0.330481,-0.194702,-0.518559,-0.016252,-0.706638,-0.908502,0.797990,0.875999,-0.330481,...,-0.706638,-0.551602,-0.706638,-0.908502,-0.706638,-1.086952,-0.706638,-1.086952,-0.706638,-0.373152
117,Remitted,0.609911,0.875999,0.986068,-0.551602,0.045676,-0.730052,-0.518559,-0.730052,0.233755,...,2.114539,-0.373152,1.550304,1.054449,1.174147,0.519099,0.609911,-0.373152,2.490696,0.340648
118,Remitted,0.797990,1.768249,-0.142402,1.946699,0.421833,0.697549,0.986068,0.162198,1.926461,...,0.421833,2.482050,0.609911,-0.373152,-0.518559,-0.373152,0.609911,1.232899,2.114539,0.875999
119,Remitted,0.797990,1.946699,-0.330481,0.340648,0.421833,1.589799,0.233755,2.660500,-0.518559,...,-0.330481,0.697549,-0.518559,0.697549,2.114539,1.411349,-0.142402,-0.194702,0.421833,0.162198

In [6]:
#read test data
test_data = pd.read_csv(REAL_DATA_HOME + '0_Depression_Data_Real_Test.csv')
for col in categorical_columns :
    test_data[col] = test_data[col].astype('category')
test_data

,group,ma1,hars1,ma2,hars2,ma3,hars3,ma4,hars4,ma5,...,ma10,hars10,ma11,hars11,ma12,hars12,ma13,hars13,ma14,hars14
0,Remitted,-0.309550,-0.569420,-0.872369,-0.756370,-0.497156,-0.008569,-0.684762,0.178382,-0.121944,...,0.065662,-0.008569,1.566511,-0.008569,0.440874,-0.569420,-0.309550,0.178382,-0.121944,0.178382
1,Remitted,0.065662,0.178382,-0.309550,-0.569420,-0.497156,-0.382469,0.253268,-0.195519,-0.497156,...,-0.497156,-0.382469,-0.497156,-0.756370,-0.684762,-0.382469,-0.872369,-0.195519,-0.309550,0.739233
2,Remitted,-0.684762,-0.943320,-0.309550,-0.569420,-0.497156,-0.943320,-0.121944,-0.756370,-0.497156,...,-0.872369,-0.382469,-0.309550,-0.195519,-0.121944,-0.382469,-0.309550,-0.569420,-0.497156,-0.382469
3,Remitted,0.440874,-0.195519,1.003693,0.552282,0.440874,-0.569420,0.440874,-0.569420,-0.121944,...,0.440874,0.365332,-0.684762,-0.756370,0.065662,-0.008569,-0.497156,-0.195519,-0.121944,-0.008569
4,Remitted,1.003693,0.365332,-0.309550,-0.756370,2.879754,2.982637,0.816087,-0.195519,0.065662,...,-0.497156,-0.569420,-0.684762,-0.569420,0.065662,-0.943320,-0.309550,-0.569420,0.628481,0.365332
5,Remitted,0.440874,0.178382,-0.309550,-0.569420,0.628481,-0.382469,1.191299,0.739233,0.065662,...,-0.872369,-0.195519,-0.684762,-0.195519,-0.121944,0.552282,-0.872369,-0.382469,-0.497156,-0.382469
6,Remitted,-0.684762,0.365332,0.816087,0.739233,-0.309550,0.365332,0.816087,1.300084,0.253268,...,-0.309550,0.178382,-0.121944,0.739233,0.065662,-0.008569,-0.121944,-0.569420,-0.309550,1.113133
7,Remitted,-0.309550,-0.569420,-0.121944,-0.569420,-0.872369,-0.756370,-0.684762,-0.569420,-0.872369,...,-0.497156,-0.569420,-0.872369,-1.130271,-0.497156,-0.569420,-0.872369,-0.756370,0.065662,-0.008569
8,Remitted,0.628481,-0.382469,-0.309550,-0.569420,-0.497156,-0.569420,0.816087,-0.943320,1.941724,...,3.817785,1.860935,-0.872369,-0.569420,-0.684762,-1.130271,-0.309550,-1.130271,0.440874,0.552282
9,Control,-0.872369,-1.130271,-0.872369,-0.569420,-0.684762,-0.943320,-0.497156,-0.756370,-0.872369,...,-0.872369,-1.130271,-0.872369,-1.130271,-0.872369,-1.130271,-0.872369,-0.943320,-0.684762,0.178382
10,Remitted,-0.309550,-0.382469,0.065662,0.365332,2.129330,0.926183,3.817785,0.739233,4.005391,...,3.067360,1.860935,3.254966,2.234835,0.628481,0.178382,0.253268,0.552282,0.065662,1.113133
11,Control,-0.309550,-0.382469,-0.309550,0.739233,-0.121944,0.739233,0.253268,0.739233,-0.121944,...,0.065662,0.739233,-0.684762,0.178382,1.003693,1.860935,-0.872369,-0.943320,-0.121944,1.113133
12,Control,-0.684762,-0.943320,-0.872369,-0.943320,-0.872369,-1.130271,-0.497156,-0.569420,-0.872369,...,-0.684762,-1.130271,-0.872369,-0.943320,-0.872369,-0.943320,-0.872369,-0.943320,-0.872369,-0.569420
13,Control,-0.872369,-1.130271,-0.872369,-0.756370,-0.684762,-0.943320,-0.684762,-0.569420,-0.872369,...,-0.872369,-1.130271,-0.684762,-0.382469,-0.497156,-0.382469,-0.872369,-0.569420,-0.872369,-1.130271
14,Control,-0.872369,-0.943320,-0.872369,0.178382,-0.872369,-1.130271,-0.497156,-0.756370,-0.121944,...,-0.309550,-0.569420,-0.121944,-0.008569,-0.497156,-0.195519,-0.684762,-0.382469,-0.872369,-1.130271
15,Control,-0.872369,-0.569420,-0.872369,-0.569420,-0.309550,-0.943320,-0.684762,-0.943320,-0.684762,...,-0.497156,-0.756370,-0.684762,-0.943320,-0.684762,-1.130271,-0.872369,-0.943320,-0.684762,0.365332
16,Remitted,-0.497156,-0.943320,0.440874,1.113133,0.816087,0.365332,2.879754,1.300084,1.003693,...,-0.497156,-0.569420,-0.684762,-0.756370,-0.684762,-1.130271,-0.309550,-0.756370,-0.309550,0.926183
17,Remitted,-0.309550,-0.382469,-0.309550,-0.569420,-0.497156,-0.382469,-0.684762,-0.943320,1.191299,...,-0.497156,-0.569420,-0.684762,-1.130271,-0.684762,-1.130271,-0.684762,-0.943320,0.065662,0.552282
18,Remitted,-0.309550,-0.382469,0.253268,-0.195519,-0.497156,-0.943320,0.253268,-0.008569,-0.121944,...,-0.684762,-0.756370,-0.684762,-0.943320,-0.497156,-0.569420,-0.309550,-0.569420,-0.497156,-0.569420
19,Control,-0.684762,-0.943320,-0.684762,-0.569420,-0.121944,-0.569420,-0.497156,-0.382469,-0.497156,...,-0.497156,-0.382469,-0.684762,-0.756370,-0.872369,-0.756370,-0.497156,-0.756370,-0.684762,-0.382469
20,Control,0.253268,0.178382,0.253268,1.113133,-0.309550,-0.756370,-0.121944,-0.008569,-0.121944,...,-0.309550,0.552282,-0.121944,0.178382,-0.309550,0.739233,-0.121944,0.739233,0.065662,0.365332
21,Remitted,-0.121944,0.178382,-0.121944,-0.008569,1.003693,0.178382,3.254966,1.860935,1.003693,...,0.628481,-0.382469,0.628481,1.860935,2.129330,1.487034,4.005391,2.982637,2.504542,2.047885
22,Control,-0.684762,-0.943320,-0.872369,-0.756370,-0.872369,-1.130271,-0.872369,-1.130271,-0.872369,...,-0.684762,-0.756370,-0.684762,-0.943320,-0.684762,-0.943320,-0.872369,-1.130271,-0.497156,0.365332
23,Remitted,0.253268,-0.008569,1.003693,3.543488,3.254966,3.917388,2.504542,5.039090,1.003693,...,-0.497156,-0.569420,-0.684762,-0.943320,0.065662,-0.195519,0.816087,0.365332,-0.121944,1.300084

In [8]:
target = 'group'
#quick look at the breakdown of class values
print('Train data')
print(train_data.shape)
print(train_data.groupby(target).size())
print('#####################################')
print('Test data')
print(test_data.shape)
print(test_data.groupby(target).size())

Train data
(120, 29)
group
Control     40
Remitted    80
dtype: int64
#####################################
Test data
(24, 29)
group
Control      9
Remitted    15
dtype: int64

## 2. Pre-process training data

In [9]:
target = 'group'
categorical_columns = []
numerical_columns = train_data.select_dtypes(include=['int64','float64']).columns.tolist()
categories = [np.array(range(2))] if categorical_columns else []
data_preprocessor = DataPreProcessor(categorical_columns, numerical_columns, categories)
x_train = data_preprocessor.preprocess_train_data(train_data.loc[:, train_data.columns != target])
y_train = train_data.loc[:, target]

x_train.shape, y_train.shape

((120, 28), (120,))

## 3. Preprocess test data

In [10]:
x_test = data_preprocessor.preprocess_test_data(test_data.loc[:, test_data.columns != target])
y_test = test_data.loc[:, target]
x_test.shape, y_test.shape

((24, 28), (24,))

## 4. Create a dataset to save the results

In [11]:
results = pd.DataFrame(columns = ['model','accuracy','precision','recall','f1'])
results

Empty DataFrame
Columns: [model, accuracy, precision, recall, f1]
Index: []

## 4. Train and evaluate Random Forest Classifier

In [12]:
rf_results = train_evaluate_model('RF', x_train, y_train, x_test, y_test)
results = pd.concat([results, rf_results], ignore_index=True)
rf_results

[Parallel(n_jobs=3)]: Using backend ThreadingBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done  44 tasks      | elapsed:    0.0s
[Parallel(n_jobs=3)]: Done 100 out of 100 | elapsed:    0.1s finished
[Parallel(n_jobs=3)]: Using backend ThreadingBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done  44 tasks      | elapsed:    0.0s
[Parallel(n_jobs=3)]: Done 100 out of 100 | elapsed:    0.0s finished

  model  accuracy  precision  recall      f1
0    RF    0.9167     0.9265  0.9167  0.9141

## 5. Train and Evaluate KNeighbors Classifier

In [13]:
knn_results = train_evaluate_model('KNN', x_train, y_train, x_test, y_test)
results = pd.concat([results, knn_results], ignore_index=True)
knn_results

  model  accuracy  precision  recall      f1
0   KNN      0.75     0.7675    0.75  0.7536

## 6. Train and evaluate Decision Tree Classifier

In [14]:
dt_results = train_evaluate_model('DT', x_train, y_train, x_test, y_test)
results = pd.concat([results, dt_results], ignore_index=True)
dt_results

  model  accuracy  precision  recall      f1
0    DT    0.7917     0.7982  0.7917  0.7936

## 7. Train and evaluate Support Vector Machines Classifier

In [15]:
svm_results = train_evaluate_model('SVM', x_train, y_train, x_test, y_test)
results = pd.concat([results, svm_results], ignore_index=True)
svm_results

[LibSVM].*.*
optimization finished, #iter = 214
obj = -3.197824, rho = -1.901500
nSV = 22, nBSV = 0
Total nSV = 22
.*.*
optimization finished, #iter = 252
obj = -5.015257, rho = -2.857821
nSV = 17, nBSV = 0
Total nSV = 17
.*.*
optimization finished, #iter = 255
obj = -4.973454, rho = -2.650100
nSV = 17, nBSV = 0
Total nSV = 17
..*.*
optimization finished, #iter = 291
obj = -4.479718, rho = -2.180416
nSV = 18, nBSV = 0
Total nSV = 18
.*
optimization finished, #iter = 175
obj = -3.159450, rho = -2.228578
nSV = 17, nBSV = 0
Total nSV = 17
..WARN: libsvm Solver reached max_iter
optimization finished, #iter = 300
obj = -5.208598, rho = 2.832919
nSV = 20, nBSV = 0
Total nSV = 20

  model  accuracy  precision  recall      f1
0   SVM     0.875     0.8804   0.875  0.8761

## 8. Train and evaluate Multilayer Perceptron Classifier

In [16]:
mlp_results = train_evaluate_model('MLP', x_train, y_train, x_test, y_test)
results = pd.concat([results, mlp_results], ignore_index=True)
mlp_results

Iteration 1, loss = 0.65591059
Iteration 2, loss = 0.61076731
Iteration 3, loss = 0.57248001
Iteration 4, loss = 0.53947383
Iteration 5, loss = 0.51012439
Iteration 6, loss = 0.48344613
Iteration 7, loss = 0.45894967
Iteration 8, loss = 0.43601766
Iteration 9, loss = 0.41428328
Iteration 10, loss = 0.39368462
Iteration 11, loss = 0.37436101
Iteration 12, loss = 0.35611327
Iteration 13, loss = 0.33894520
Iteration 14, loss = 0.32274936
Iteration 15, loss = 0.30751760
Iteration 16, loss = 0.29323730
Iteration 17, loss = 0.27959679
Iteration 18, loss = 0.26662325
Iteration 19, loss = 0.25436897
Iteration 20, loss = 0.24251443
Iteration 21, loss = 0.23117797
Iteration 22, loss = 0.22023191
Iteration 23, loss = 0.20957246
Iteration 24, loss = 0.19915997
Iteration 25, loss = 0.18889241
Iteration 26, loss = 0.17886053
Iteration 27, loss = 0.16921117
Iteration 28, loss = 0.15999746
Iteration 29, loss = 0.15120981
Iteration 30, loss = 0.14281363
Iteration 31, loss = 0.13489743
Iteration 32, loss = 0.12733527
Iteration 33, loss = 0.12020306
Iteration 34, loss = 0.11344755
Iteration 35, loss = 0.10702826
Iteration 36, loss = 0.10084050
Iteration 37, loss = 0.09494786
Iteration 38, loss = 0.08941108
Iteration 39, loss = 0.08426422
Iteration 40, loss = 0.07941453
Iteration 41, loss = 0.07487950
Iteration 42, loss = 0.07055926
Iteration 43, loss = 0.06639022
Iteration 44, loss = 0.06248906
Iteration 45, loss = 0.05882007
Iteration 46, loss = 0.05537822
Iteration 47, loss = 0.05208539
Iteration 48, loss = 0.04892483
Iteration 49, loss = 0.04588474
Iteration 50, loss = 0.04295262
Iteration 51, loss = 0.04015506
Iteration 52, loss = 0.03749900
Iteration 53, loss = 0.03497857
Iteration 54, loss = 0.03264213
Iteration 55, loss = 0.03044876
Iteration 56, loss = 0.02838932
Iteration 57, loss = 0.02644213
Iteration 58, loss = 0.02460799
Iteration 59, loss = 0.02287824
Iteration 60, loss = 0.02126203
Iteration 61, loss = 0.01975525
Iteration 62, loss = 0.01836570
Iteration 63, loss = 0.01707666
Iteration 64, loss = 0.01587904
Iteration 65, loss = 0.01476537
Iteration 66, loss = 0.01373462
Iteration 67, loss = 0.01278334
Iteration 68, loss = 0.01190217
Iteration 69, loss = 0.01108189
Iteration 70, loss = 0.01032830
Iteration 71, loss = 0.00963838
Iteration 72, loss = 0.00900179
Iteration 73, loss = 0.00841524
Iteration 74, loss = 0.00787133
Iteration 75, loss = 0.00736188
Iteration 76, loss = 0.00689130
Iteration 77, loss = 0.00646210
Iteration 78, loss = 0.00606818
Iteration 79, loss = 0.00570196
Iteration 80, loss = 0.00536369
Iteration 81, loss = 0.00505246
Iteration 82, loss = 0.00476578
Iteration 83, loss = 0.00450369
Iteration 84, loss = 0.00426289
Iteration 85, loss = 0.00404220
Iteration 86, loss = 0.00383892
Iteration 87, loss = 0.00365048
Iteration 88, loss = 0.00347612
Iteration 89, loss = 0.00331592
Iteration 90, loss = 0.00316771
Iteration 91, loss = 0.00303034
Iteration 92, loss = 0.00290448
Iteration 93, loss = 0.00278855
Iteration 94, loss = 0.00268061
Iteration 95, loss = 0.00258007
Iteration 96, loss = 0.00248622
Iteration 97, loss = 0.00239815
Iteration 98, loss = 0.00231534
Iteration 99, loss = 0.00223743
Iteration 100, loss = 0.00216402
Iteration 101, loss = 0.00209491
Iteration 102, loss = 0.00203006
Iteration 103, loss = 0.00196924
Iteration 104, loss = 0.00191174
Iteration 105, loss = 0.00185729
Iteration 106, loss = 0.00180558
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.

  model  accuracy  precision  recall      f1
0   MLP    0.9167     0.9167  0.9167  0.9167

## 9. Save results file

In [17]:
results.to_csv('RESULTS/models_results_ECDF.csv', index=False)
results

  model  accuracy  precision  recall      f1
0    RF    0.9167     0.9265  0.9167  0.9141
1   KNN    0.7500     0.7675  0.7500  0.7536
2    DT    0.7917     0.7982  0.7917  0.7936
3   SVM    0.8750     0.8804  0.8750  0.8761
4   MLP    0.9167     0.9167  0.9167  0.9167