# TSTR GM Dataset 0 - REMBRANDT

In [1]:
#import libraries
import warnings
warnings.filterwarnings("ignore")
import numpy as np
import pandas as pd
import os
print('Libraries imported!!')

Libraries imported!!

In [2]:
#define directory of functions and actual directory
FUNCTIONS_HOME = '../../../functions/evaluation_functions/' #home directory of the project
REAL_DATA_HOME = '../../../data/raw/rembrandt/' #home directory of the project
SYN_DATA_HOME  = '../../../data/processed/rembrandt/' #home directory of the project
FUNCTIONS_DIR = 'EVALUATION FUNCTIONS/UTILITY'
ACTUAL_DIR = os.getcwd()

#change directory to functions directory
os.chdir(FUNCTIONS_HOME + FUNCTIONS_DIR)

#import functions for data labelling analisys
from utility_evaluation import DataPreProcessor
from utility_evaluation import train_evaluate_model

#change directory to actual directory
os.chdir(ACTUAL_DIR)
print('Functions imported!!')

Functions imported!!

## 1. Read data

In [3]:
#read real dataset
train_data = pd.read_csv(SYN_DATA_HOME + '0_Depression_Data_Synthetic_GM.csv')
categorical_columns = ['group']
for col in categorical_columns :
    train_data[col] = train_data[col].astype('category')
train_data

,group,ma1,hars1,ma2,hars2,ma3,hars3,ma4,hars4,ma5,...,ma10,hars10,ma11,hars11,ma12,hars12,ma13,hars13,ma14,hars14
0,Remitted,0.205875,1.666929,0.027499,0.812336,2.143901,2.371067,0.325139,0.358222,2.339175,...,-0.266378,2.205005,0.415031,0.656864,-0.791394,-0.833291,0.087396,1.589851,0.135561,0.575611
1,Control,-0.711492,-0.695166,-0.978856,-0.986423,-1.238163,-1.360812,-0.675340,-0.683794,-0.467972,...,-0.597241,-1.046943,-0.806604,-1.751534,-0.805991,-1.660750,-0.827117,-0.732491,-0.695939,-1.860239
2,Control,-0.666669,0.144931,-0.815925,-0.781343,1.773360,1.463537,0.634446,0.529802,1.524290,...,0.033502,2.652962,2.051664,3.407842,1.522785,3.122808,3.237207,2.391341,0.026513,0.639414
3,Remitted,-0.789575,-0.225257,-0.168826,0.342664,-1.051718,-0.438112,0.013381,1.647405,-1.105866,...,-0.501686,0.213281,-0.864295,-0.150831,-0.247579,-0.146039,-0.481964,-0.535933,-0.355955,0.011270
4,Control,-0.523823,-0.156905,-0.353042,-0.526743,-0.534734,0.484559,-0.007897,0.006802,-0.306415,...,-0.637426,0.132826,0.473707,0.792979,-0.467661,-0.177332,-0.097979,-0.397791,-0.717832,-0.030366
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,Remitted,0.072537,1.320036,-0.360072,-0.445960,0.994687,1.414214,-0.083550,0.772456,0.001498,...,-0.416074,0.838366,-0.068896,1.539587,-0.755726,-0.345174,0.073679,0.566898,-0.074234,0.957388
92,Remitted,-0.843856,-0.867316,-0.590182,-0.869050,0.214753,-0.093671,-0.028980,-0.725966,-0.825706,...,-0.771105,-1.081811,-0.847669,-1.583679,-0.745442,-1.054146,-0.581273,-1.136829,-0.749949,-0.585377
93,Remitted,0.246558,1.115083,1.275956,11.950878,0.691709,1.287503,-1.103111,-0.796453,-0.456246,...,-0.739724,-0.892254,-0.871645,-1.245003,-0.871462,-1.298774,-1.553615,-1.465718,-1.347361,-0.290510
94,Remitted,-0.800517,-0.021533,-0.223322,-0.738683,0.573506,1.289456,0.702364,1.180324,-0.326154,...,1.455113,1.256310,-0.108082,0.093772,0.266940,-0.022149,1.088528,0.187968,0.610327,1.213997
95,Control,-1.427242,-0.475675,-1.276583,-1.071552,-1.194664,-0.650174,-0.949322,-0.842159,-1.028060,...,-0.634676,-0.947780,-0.748411,-0.577158,-0.693602,-0.671331,-0.971480,-1.060722,-0.783056,-0.792272

In [4]:
#read test data
test_data = pd.read_csv(REAL_DATA_HOME + '0_Depression_Data_Real_Test.csv')
for col in categorical_columns :
    test_data[col] = test_data[col].astype('category')
test_data

,group,ma1,hars1,ma2,hars2,ma3,hars3,ma4,hars4,ma5,...,ma10,hars10,ma11,hars11,ma12,hars12,ma13,hars13,ma14,hars14
0,Remitted,-0.309550,-0.569420,-0.872369,-0.756370,-0.497156,-0.008569,-0.684762,0.178382,-0.121944,...,0.065662,-0.008569,1.566511,-0.008569,0.440874,-0.569420,-0.309550,0.178382,-0.121944,0.178382
1,Remitted,0.065662,0.178382,-0.309550,-0.569420,-0.497156,-0.382469,0.253268,-0.195519,-0.497156,...,-0.497156,-0.382469,-0.497156,-0.756370,-0.684762,-0.382469,-0.872369,-0.195519,-0.309550,0.739233
2,Remitted,-0.684762,-0.943320,-0.309550,-0.569420,-0.497156,-0.943320,-0.121944,-0.756370,-0.497156,...,-0.872369,-0.382469,-0.309550,-0.195519,-0.121944,-0.382469,-0.309550,-0.569420,-0.497156,-0.382469
3,Remitted,0.440874,-0.195519,1.003693,0.552282,0.440874,-0.569420,0.440874,-0.569420,-0.121944,...,0.440874,0.365332,-0.684762,-0.756370,0.065662,-0.008569,-0.497156,-0.195519,-0.121944,-0.008569
4,Remitted,1.003693,0.365332,-0.309550,-0.756370,2.879754,2.982637,0.816087,-0.195519,0.065662,...,-0.497156,-0.569420,-0.684762,-0.569420,0.065662,-0.943320,-0.309550,-0.569420,0.628481,0.365332
5,Remitted,0.440874,0.178382,-0.309550,-0.569420,0.628481,-0.382469,1.191299,0.739233,0.065662,...,-0.872369,-0.195519,-0.684762,-0.195519,-0.121944,0.552282,-0.872369,-0.382469,-0.497156,-0.382469
6,Remitted,-0.684762,0.365332,0.816087,0.739233,-0.309550,0.365332,0.816087,1.300084,0.253268,...,-0.309550,0.178382,-0.121944,0.739233,0.065662,-0.008569,-0.121944,-0.569420,-0.309550,1.113133
7,Remitted,-0.309550,-0.569420,-0.121944,-0.569420,-0.872369,-0.756370,-0.684762,-0.569420,-0.872369,...,-0.497156,-0.569420,-0.872369,-1.130271,-0.497156,-0.569420,-0.872369,-0.756370,0.065662,-0.008569
8,Remitted,0.628481,-0.382469,-0.309550,-0.569420,-0.497156,-0.569420,0.816087,-0.943320,1.941724,...,3.817785,1.860935,-0.872369,-0.569420,-0.684762,-1.130271,-0.309550,-1.130271,0.440874,0.552282
9,Control,-0.872369,-1.130271,-0.872369,-0.569420,-0.684762,-0.943320,-0.497156,-0.756370,-0.872369,...,-0.872369,-1.130271,-0.872369,-1.130271,-0.872369,-1.130271,-0.872369,-0.943320,-0.684762,0.178382
10,Remitted,-0.309550,-0.382469,0.065662,0.365332,2.129330,0.926183,3.817785,0.739233,4.005391,...,3.067360,1.860935,3.254966,2.234835,0.628481,0.178382,0.253268,0.552282,0.065662,1.113133
11,Control,-0.309550,-0.382469,-0.309550,0.739233,-0.121944,0.739233,0.253268,0.739233,-0.121944,...,0.065662,0.739233,-0.684762,0.178382,1.003693,1.860935,-0.872369,-0.943320,-0.121944,1.113133
12,Control,-0.684762,-0.943320,-0.872369,-0.943320,-0.872369,-1.130271,-0.497156,-0.569420,-0.872369,...,-0.684762,-1.130271,-0.872369,-0.943320,-0.872369,-0.943320,-0.872369,-0.943320,-0.872369,-0.569420
13,Control,-0.872369,-1.130271,-0.872369,-0.756370,-0.684762,-0.943320,-0.684762,-0.569420,-0.872369,...,-0.872369,-1.130271,-0.684762,-0.382469,-0.497156,-0.382469,-0.872369,-0.569420,-0.872369,-1.130271
14,Control,-0.872369,-0.943320,-0.872369,0.178382,-0.872369,-1.130271,-0.497156,-0.756370,-0.121944,...,-0.309550,-0.569420,-0.121944,-0.008569,-0.497156,-0.195519,-0.684762,-0.382469,-0.872369,-1.130271
15,Control,-0.872369,-0.569420,-0.872369,-0.569420,-0.309550,-0.943320,-0.684762,-0.943320,-0.684762,...,-0.497156,-0.756370,-0.684762,-0.943320,-0.684762,-1.130271,-0.872369,-0.943320,-0.684762,0.365332
16,Remitted,-0.497156,-0.943320,0.440874,1.113133,0.816087,0.365332,2.879754,1.300084,1.003693,...,-0.497156,-0.569420,-0.684762,-0.756370,-0.684762,-1.130271,-0.309550,-0.756370,-0.309550,0.926183
17,Remitted,-0.309550,-0.382469,-0.309550,-0.569420,-0.497156,-0.382469,-0.684762,-0.943320,1.191299,...,-0.497156,-0.569420,-0.684762,-1.130271,-0.684762,-1.130271,-0.684762,-0.943320,0.065662,0.552282
18,Remitted,-0.309550,-0.382469,0.253268,-0.195519,-0.497156,-0.943320,0.253268,-0.008569,-0.121944,...,-0.684762,-0.756370,-0.684762,-0.943320,-0.497156,-0.569420,-0.309550,-0.569420,-0.497156,-0.569420
19,Control,-0.684762,-0.943320,-0.684762,-0.569420,-0.121944,-0.569420,-0.497156,-0.382469,-0.497156,...,-0.497156,-0.382469,-0.684762,-0.756370,-0.872369,-0.756370,-0.497156,-0.756370,-0.684762,-0.382469
20,Control,0.253268,0.178382,0.253268,1.113133,-0.309550,-0.756370,-0.121944,-0.008569,-0.121944,...,-0.309550,0.552282,-0.121944,0.178382,-0.309550,0.739233,-0.121944,0.739233,0.065662,0.365332
21,Remitted,-0.121944,0.178382,-0.121944,-0.008569,1.003693,0.178382,3.254966,1.860935,1.003693,...,0.628481,-0.382469,0.628481,1.860935,2.129330,1.487034,4.005391,2.982637,2.504542,2.047885
22,Control,-0.684762,-0.943320,-0.872369,-0.756370,-0.872369,-1.130271,-0.872369,-1.130271,-0.872369,...,-0.684762,-0.756370,-0.684762,-0.943320,-0.684762,-0.943320,-0.872369,-1.130271,-0.497156,0.365332
23,Remitted,0.253268,-0.008569,1.003693,3.543488,3.254966,3.917388,2.504542,5.039090,1.003693,...,-0.497156,-0.569420,-0.684762,-0.943320,0.065662,-0.195519,0.816087,0.365332,-0.121944,1.300084

In [5]:
target = 'group'
#quick look at the breakdown of class values
print('Train data')
print(train_data.shape)
print(train_data.groupby(target).size())
print('#####################################')
print('Test data')
print(test_data.shape)
print(test_data.groupby(target).size())

Train data
(96, 29)
group
Control     35
Remitted    61
dtype: int64
#####################################
Test data
(24, 29)
group
Control      9
Remitted    15
dtype: int64

## 2. Pre-process training data

In [6]:
target = 'group'
categorical_columns = []
numerical_columns = train_data.select_dtypes(include=['int64','float64']).columns.tolist()
categories = [np.array(range(2))] if categorical_columns else []
data_preprocessor = DataPreProcessor(categorical_columns, numerical_columns, categories)
x_train = data_preprocessor.preprocess_train_data(train_data.loc[:, train_data.columns != target])
y_train = train_data.loc[:, target]

x_train.shape, y_train.shape

((96, 28), (96,))

## 3. Preprocess test data

In [7]:
x_test = data_preprocessor.preprocess_test_data(test_data.loc[:, test_data.columns != target])
y_test = test_data.loc[:, target]
x_test.shape, y_test.shape

((24, 28), (24,))

## 4. Create a dataset to save the results

In [8]:
results = pd.DataFrame(columns = ['model','accuracy','precision','recall','f1'])
results

Empty DataFrame
Columns: [model, accuracy, precision, recall, f1]
Index: []

## 4. Train and evaluate Random Forest Classifier

In [9]:
rf_results = train_evaluate_model('RF', x_train, y_train, x_test, y_test)
results = pd.concat([results, rf_results], ignore_index=True)
rf_results

[Parallel(n_jobs=3)]: Using backend ThreadingBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done  44 tasks      | elapsed:    0.0s
[Parallel(n_jobs=3)]: Done 100 out of 100 | elapsed:    0.1s finished
[Parallel(n_jobs=3)]: Using backend ThreadingBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done  44 tasks      | elapsed:    0.0s
[Parallel(n_jobs=3)]: Done 100 out of 100 | elapsed:    0.0s finished

  model  accuracy  precision  recall      f1
0    RF     0.875      0.875   0.875  0.8733

## 5. Train and Evaluate KNeighbors Classifier

In [10]:
knn_results = train_evaluate_model('KNN', x_train, y_train, x_test, y_test)
results = pd.concat([results, knn_results], ignore_index=True)
knn_results

  model  accuracy  precision  recall      f1
0   KNN     0.875      0.875   0.875  0.8733

## 6. Train and evaluate Decision Tree Classifier

In [11]:
dt_results = train_evaluate_model('DT', x_train, y_train, x_test, y_test)
results = pd.concat([results, dt_results], ignore_index=True)
dt_results

  model  accuracy  precision  recall      f1
0    DT    0.7917     0.7982  0.7917  0.7936

## 7. Train and evaluate Support Vector Machines Classifier

In [12]:
svm_results = train_evaluate_model('SVM', x_train, y_train, x_test, y_test)
results = pd.concat([results, svm_results], ignore_index=True)
svm_results

[LibSVM]...WARN: libsvm Solver reached max_iter
optimization finished, #iter = 300
obj = -61.116580, rho = -3.275661
nSV = 23, nBSV = 0
Total nSV = 23
...WARN: libsvm Solver reached max_iter
optimization finished, #iter = 300
obj = -34.662173, rho = -2.780016
nSV = 29, nBSV = 0
Total nSV = 29
...WARN: libsvm Solver reached max_iter
optimization finished, #iter = 300
obj = -105.627759, rho = -1.778732
nSV = 34, nBSV = 0
Total nSV = 34
...WARN: libsvm Solver reached max_iter
optimization finished, #iter = 300
obj = -51.946967, rho = -2.104836
nSV = 32, nBSV = 0
Total nSV = 32
...WARN: libsvm Solver reached max_iter
optimization finished, #iter = 300
obj = -30.592861, rho = -2.779827
nSV = 24, nBSV = 0
Total nSV = 24
...WARN: libsvm Solver reached max_iter
optimization finished, #iter = 300
obj = -93.412036, rho = 1.405425
nSV = 44, nBSV = 0
Total nSV = 44

  model  accuracy  precision  recall      f1
0   SVM    0.9167     0.9167  0.9167  0.9167

## 8. Train and evaluate Multilayer Perceptron Classifier

In [13]:
mlp_results = train_evaluate_model('MLP', x_train, y_train, x_test, y_test)
results = pd.concat([results, mlp_results], ignore_index=True)
mlp_results

Iteration 1, loss = 0.68375118
Iteration 2, loss = 0.64742906
Iteration 3, loss = 0.61659593
Iteration 4, loss = 0.59114202
Iteration 5, loss = 0.56967256
Iteration 6, loss = 0.55099315
Iteration 7, loss = 0.53485270
Iteration 8, loss = 0.52011510
Iteration 9, loss = 0.50630965
Iteration 10, loss = 0.49303478
Iteration 11, loss = 0.48056693
Iteration 12, loss = 0.46852523
Iteration 13, loss = 0.45669110
Iteration 14, loss = 0.44486128
Iteration 15, loss = 0.43321806
Iteration 16, loss = 0.42162871
Iteration 17, loss = 0.40967816
Iteration 18, loss = 0.39751108
Iteration 19, loss = 0.38500055
Iteration 20, loss = 0.37254845
Iteration 21, loss = 0.35986647
Iteration 22, loss = 0.34733787
Iteration 23, loss = 0.33515366
Iteration 24, loss = 0.32298475
Iteration 25, loss = 0.31085468
Iteration 26, loss = 0.29885161
Iteration 27, loss = 0.28699492
Iteration 28, loss = 0.27521840
Iteration 29, loss = 0.26356109
Iteration 30, loss = 0.25195037
Iteration 31, loss = 0.24046887
Iteration 32, loss = 0.22923552
Iteration 33, loss = 0.21812187
Iteration 34, loss = 0.20712788
Iteration 35, loss = 0.19626598
Iteration 36, loss = 0.18574154
Iteration 37, loss = 0.17552051
Iteration 38, loss = 0.16546591
Iteration 39, loss = 0.15579406
Iteration 40, loss = 0.14653959
Iteration 41, loss = 0.13759021
Iteration 42, loss = 0.12895946
Iteration 43, loss = 0.12065308
Iteration 44, loss = 0.11267633
Iteration 45, loss = 0.10510058
Iteration 46, loss = 0.09794670
Iteration 47, loss = 0.09110496
Iteration 48, loss = 0.08462508
Iteration 49, loss = 0.07845940
Iteration 50, loss = 0.07256538
Iteration 51, loss = 0.06687136
Iteration 52, loss = 0.06140686
Iteration 53, loss = 0.05628181
Iteration 54, loss = 0.05155639
Iteration 55, loss = 0.04721581
Iteration 56, loss = 0.04321617
Iteration 57, loss = 0.03951468
Iteration 58, loss = 0.03612216
Iteration 59, loss = 0.03301320
Iteration 60, loss = 0.03018250
Iteration 61, loss = 0.02763407
Iteration 62, loss = 0.02532548
Iteration 63, loss = 0.02321541
Iteration 64, loss = 0.02129223
Iteration 65, loss = 0.01954345
Iteration 66, loss = 0.01795587
Iteration 67, loss = 0.01652251
Iteration 68, loss = 0.01521884
Iteration 69, loss = 0.01403883
Iteration 70, loss = 0.01298027
Iteration 71, loss = 0.01202001
Iteration 72, loss = 0.01116533
Iteration 73, loss = 0.01038933
Iteration 74, loss = 0.00968626
Iteration 75, loss = 0.00905630
Iteration 76, loss = 0.00848824
Iteration 77, loss = 0.00797107
Iteration 78, loss = 0.00749922
Iteration 79, loss = 0.00706896
Iteration 80, loss = 0.00667488
Iteration 81, loss = 0.00631511
Iteration 82, loss = 0.00598164
Iteration 83, loss = 0.00567706
Iteration 84, loss = 0.00539539
Iteration 85, loss = 0.00513350
Iteration 86, loss = 0.00488993
Iteration 87, loss = 0.00466284
Iteration 88, loss = 0.00445076
Iteration 89, loss = 0.00425617
Iteration 90, loss = 0.00407779
Iteration 91, loss = 0.00391253
Iteration 92, loss = 0.00375867
Iteration 93, loss = 0.00361544
Iteration 94, loss = 0.00348220
Iteration 95, loss = 0.00335749
Iteration 96, loss = 0.00324028
Iteration 97, loss = 0.00312977
Iteration 98, loss = 0.00302588
Iteration 99, loss = 0.00292914
Iteration 100, loss = 0.00283846
Iteration 101, loss = 0.00275263
Iteration 102, loss = 0.00267180
Iteration 103, loss = 0.00259538
Iteration 104, loss = 0.00252283
Iteration 105, loss = 0.00245397
Iteration 106, loss = 0.00238842
Iteration 107, loss = 0.00232609
Iteration 108, loss = 0.00226667
Iteration 109, loss = 0.00220997
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.

  model  accuracy  precision  recall      f1
0   MLP    0.7917     0.7982  0.7917  0.7936

## 9. Save results file

In [14]:
results.to_csv('RESULTS/models_results_gm.csv', index=False)
results

  model  accuracy  precision  recall      f1
0    RF    0.8750     0.8750  0.8750  0.8733
1   KNN    0.8750     0.8750  0.8750  0.8733
2    DT    0.7917     0.7982  0.7917  0.7936
3   SVM    0.9167     0.9167  0.9167  0.9167
4   MLP    0.7917     0.7982  0.7917  0.7936