# TSTR SDV Dataset A - Diabetes

In [12]:
#import libraries
import warnings
warnings.filterwarnings("ignore")
import numpy as np
import pandas as pd
import os
print('Libraries imported!!')

Libraries imported!!

In [13]:
#define directory of functions and actual directory
FUNCTIONS_HOME = '../../../functions/evaluation_functions/' #home directory of the project
REAL_DATA_HOME = '../../../data/raw/rembrandt/' #home directory of the project
SYN_DATA_HOME  = '../../../data/processed/rembrandt/' #home directory of the project
FUNCTIONS_DIR = 'EVALUATION FUNCTIONS/UTILITY'
ACTUAL_DIR = os.getcwd()

#change directory to functions directory
os.chdir(FUNCTIONS_HOME + FUNCTIONS_DIR)
#import functions for data labelling analisys
from utility_evaluation import DataPreProcessor
from utility_evaluation import train_evaluate_model

#change directory to actual directory
os.chdir(ACTUAL_DIR)
print('Functions imported!!')

Functions imported!!

## 1. Read data

In [14]:
#read real dataset
train_data = pd.read_csv(SYN_DATA_HOME + '0_Depression_Data_Synthetic_SDV.csv')
categorical_columns = ['group']
for col in categorical_columns :
    train_data[col] = train_data[col].astype('category')
train_data

,group,ma1,hars1,ma2,hars2,ma3,hars3,ma4,hars4,ma5,...,ma10,hars10,ma11,hars11,ma12,hars12,ma13,hars13,ma14,hars14
0,Control,-0.526552,-0.503796,-0.126666,-0.945849,-0.626173,-0.726882,-0.736136,-0.224037,-0.872369,...,-0.699358,-1.130271,-0.872369,-0.420513,-0.781141,-1.130271,-0.768524,-0.431702,-0.496995,0.298801
1,Remitted,0.499846,-1.050591,-0.784461,-0.440538,-0.872369,-0.403508,-0.443969,0.325958,-0.559629,...,0.133816,0.054624,-0.021047,-0.283188,-0.062218,-0.152891,0.031533,-0.673691,-0.486443,0.902377
2,Control,-0.650528,-0.567976,-0.109932,-1.130271,-0.872369,-0.708940,-0.640638,-1.086052,-0.872369,...,-0.759087,-0.716348,-0.842848,0.057614,-0.776351,-1.130271,-0.862435,-0.536475,-0.584379,-0.092364
3,Remitted,-0.483030,0.136977,0.071759,-0.748899,-0.332061,-1.130271,-0.872369,-0.727835,-0.574798,...,-0.872369,-0.402823,-0.715093,0.401735,0.056658,-0.996791,0.652423,-0.460742,0.087988,0.484143
4,Remitted,-0.555929,0.308327,0.127175,-1.130271,-0.872369,-1.130271,-0.361144,-0.394663,-0.196802,...,-0.004736,0.091620,-0.545564,0.700549,1.158322,-0.619900,-0.135528,-0.135439,0.714020,2.101786
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,Remitted,-0.872369,-0.619289,-0.429254,-1.130271,-0.330076,-1.026647,0.611028,-1.130271,-0.665150,...,0.550627,-0.583594,0.389302,0.410925,-0.450053,0.238073,-0.539901,-0.217269,-0.171806,-0.003442
92,Remitted,-0.166857,-0.100871,0.698290,0.392797,-0.872369,0.546166,-0.872369,2.088493,-0.692367,...,-0.520623,-0.646057,-0.745771,0.518750,0.882050,-0.064612,0.039119,-0.685416,-0.288388,-0.129392
93,Remitted,-0.496410,-1.083076,-0.159674,-0.640737,-0.292132,-1.130271,0.355127,-1.130271,0.756840,...,0.255831,-1.130271,-0.006122,-0.847448,-0.513357,-0.358624,0.108123,0.056153,-0.518733,1.070489
94,Remitted,-0.358288,-0.471478,-0.872369,-0.347409,-0.407199,-0.209311,-0.872369,0.320983,0.290484,...,0.642659,-0.339742,-0.047930,0.332537,-0.201837,-0.117477,-0.175351,-0.666752,0.402782,0.264831
95,Remitted,0.283914,-1.130271,-0.446623,-0.418051,-0.872369,-0.597681,-0.872369,-0.871649,-0.621248,...,-0.872369,-0.052751,-0.557971,-0.781707,-0.872369,-0.819959,-0.678801,-0.282563,0.114510,-0.296020

In [15]:
#read test data
test_data = pd.read_csv(REAL_DATA_HOME + '0_Depression_Data_Real_Test.csv')
for col in categorical_columns :
    test_data[col] = test_data[col].astype('category')
test_data

,group,ma1,hars1,ma2,hars2,ma3,hars3,ma4,hars4,ma5,...,ma10,hars10,ma11,hars11,ma12,hars12,ma13,hars13,ma14,hars14
0,Remitted,-0.309550,-0.569420,-0.872369,-0.756370,-0.497156,-0.008569,-0.684762,0.178382,-0.121944,...,0.065662,-0.008569,1.566511,-0.008569,0.440874,-0.569420,-0.309550,0.178382,-0.121944,0.178382
1,Remitted,0.065662,0.178382,-0.309550,-0.569420,-0.497156,-0.382469,0.253268,-0.195519,-0.497156,...,-0.497156,-0.382469,-0.497156,-0.756370,-0.684762,-0.382469,-0.872369,-0.195519,-0.309550,0.739233
2,Remitted,-0.684762,-0.943320,-0.309550,-0.569420,-0.497156,-0.943320,-0.121944,-0.756370,-0.497156,...,-0.872369,-0.382469,-0.309550,-0.195519,-0.121944,-0.382469,-0.309550,-0.569420,-0.497156,-0.382469
3,Remitted,0.440874,-0.195519,1.003693,0.552282,0.440874,-0.569420,0.440874,-0.569420,-0.121944,...,0.440874,0.365332,-0.684762,-0.756370,0.065662,-0.008569,-0.497156,-0.195519,-0.121944,-0.008569
4,Remitted,1.003693,0.365332,-0.309550,-0.756370,2.879754,2.982637,0.816087,-0.195519,0.065662,...,-0.497156,-0.569420,-0.684762,-0.569420,0.065662,-0.943320,-0.309550,-0.569420,0.628481,0.365332
5,Remitted,0.440874,0.178382,-0.309550,-0.569420,0.628481,-0.382469,1.191299,0.739233,0.065662,...,-0.872369,-0.195519,-0.684762,-0.195519,-0.121944,0.552282,-0.872369,-0.382469,-0.497156,-0.382469
6,Remitted,-0.684762,0.365332,0.816087,0.739233,-0.309550,0.365332,0.816087,1.300084,0.253268,...,-0.309550,0.178382,-0.121944,0.739233,0.065662,-0.008569,-0.121944,-0.569420,-0.309550,1.113133
7,Remitted,-0.309550,-0.569420,-0.121944,-0.569420,-0.872369,-0.756370,-0.684762,-0.569420,-0.872369,...,-0.497156,-0.569420,-0.872369,-1.130271,-0.497156,-0.569420,-0.872369,-0.756370,0.065662,-0.008569
8,Remitted,0.628481,-0.382469,-0.309550,-0.569420,-0.497156,-0.569420,0.816087,-0.943320,1.941724,...,3.817785,1.860935,-0.872369,-0.569420,-0.684762,-1.130271,-0.309550,-1.130271,0.440874,0.552282
9,Control,-0.872369,-1.130271,-0.872369,-0.569420,-0.684762,-0.943320,-0.497156,-0.756370,-0.872369,...,-0.872369,-1.130271,-0.872369,-1.130271,-0.872369,-1.130271,-0.872369,-0.943320,-0.684762,0.178382
10,Remitted,-0.309550,-0.382469,0.065662,0.365332,2.129330,0.926183,3.817785,0.739233,4.005391,...,3.067360,1.860935,3.254966,2.234835,0.628481,0.178382,0.253268,0.552282,0.065662,1.113133
11,Control,-0.309550,-0.382469,-0.309550,0.739233,-0.121944,0.739233,0.253268,0.739233,-0.121944,...,0.065662,0.739233,-0.684762,0.178382,1.003693,1.860935,-0.872369,-0.943320,-0.121944,1.113133
12,Control,-0.684762,-0.943320,-0.872369,-0.943320,-0.872369,-1.130271,-0.497156,-0.569420,-0.872369,...,-0.684762,-1.130271,-0.872369,-0.943320,-0.872369,-0.943320,-0.872369,-0.943320,-0.872369,-0.569420
13,Control,-0.872369,-1.130271,-0.872369,-0.756370,-0.684762,-0.943320,-0.684762,-0.569420,-0.872369,...,-0.872369,-1.130271,-0.684762,-0.382469,-0.497156,-0.382469,-0.872369,-0.569420,-0.872369,-1.130271
14,Control,-0.872369,-0.943320,-0.872369,0.178382,-0.872369,-1.130271,-0.497156,-0.756370,-0.121944,...,-0.309550,-0.569420,-0.121944,-0.008569,-0.497156,-0.195519,-0.684762,-0.382469,-0.872369,-1.130271
15,Control,-0.872369,-0.569420,-0.872369,-0.569420,-0.309550,-0.943320,-0.684762,-0.943320,-0.684762,...,-0.497156,-0.756370,-0.684762,-0.943320,-0.684762,-1.130271,-0.872369,-0.943320,-0.684762,0.365332
16,Remitted,-0.497156,-0.943320,0.440874,1.113133,0.816087,0.365332,2.879754,1.300084,1.003693,...,-0.497156,-0.569420,-0.684762,-0.756370,-0.684762,-1.130271,-0.309550,-0.756370,-0.309550,0.926183
17,Remitted,-0.309550,-0.382469,-0.309550,-0.569420,-0.497156,-0.382469,-0.684762,-0.943320,1.191299,...,-0.497156,-0.569420,-0.684762,-1.130271,-0.684762,-1.130271,-0.684762,-0.943320,0.065662,0.552282
18,Remitted,-0.309550,-0.382469,0.253268,-0.195519,-0.497156,-0.943320,0.253268,-0.008569,-0.121944,...,-0.684762,-0.756370,-0.684762,-0.943320,-0.497156,-0.569420,-0.309550,-0.569420,-0.497156,-0.569420
19,Control,-0.684762,-0.943320,-0.684762,-0.569420,-0.121944,-0.569420,-0.497156,-0.382469,-0.497156,...,-0.497156,-0.382469,-0.684762,-0.756370,-0.872369,-0.756370,-0.497156,-0.756370,-0.684762,-0.382469
20,Control,0.253268,0.178382,0.253268,1.113133,-0.309550,-0.756370,-0.121944,-0.008569,-0.121944,...,-0.309550,0.552282,-0.121944,0.178382,-0.309550,0.739233,-0.121944,0.739233,0.065662,0.365332
21,Remitted,-0.121944,0.178382,-0.121944,-0.008569,1.003693,0.178382,3.254966,1.860935,1.003693,...,0.628481,-0.382469,0.628481,1.860935,2.129330,1.487034,4.005391,2.982637,2.504542,2.047885
22,Control,-0.684762,-0.943320,-0.872369,-0.756370,-0.872369,-1.130271,-0.872369,-1.130271,-0.872369,...,-0.684762,-0.756370,-0.684762,-0.943320,-0.684762,-0.943320,-0.872369,-1.130271,-0.497156,0.365332
23,Remitted,0.253268,-0.008569,1.003693,3.543488,3.254966,3.917388,2.504542,5.039090,1.003693,...,-0.497156,-0.569420,-0.684762,-0.943320,0.065662,-0.195519,0.816087,0.365332,-0.121944,1.300084

In [16]:
target = 'group'
#quick look at the breakdown of class values
print('Train data')
print(train_data.shape)
print(train_data.groupby(target).size())
print('#####################################')
print('Test data')
print(test_data.shape)
print(test_data.groupby(target).size())

Train data
(96, 29)
group
Control     33
Remitted    63
dtype: int64
#####################################
Test data
(24, 29)
group
Control      9
Remitted    15
dtype: int64

## 2. Pre-process training data

In [17]:
target = 'group'
categorical_columns = []
numerical_columns = train_data.select_dtypes(include=['int64','float64']).columns.tolist()
categories = [np.array(range(2))] if categorical_columns else []

data_preprocessor = DataPreProcessor(categorical_columns, numerical_columns, categories)
x_train = data_preprocessor.preprocess_train_data(train_data.loc[:, train_data.columns != target])
y_train = train_data.loc[:, target]

x_train.shape, y_train.shape

((96, 28), (96,))

## 3. Preprocess test data

In [18]:
x_test = data_preprocessor.preprocess_test_data(test_data.loc[:, test_data.columns != target])
y_test = test_data.loc[:, target]
x_test.shape, y_test.shape

((24, 28), (24,))

## 4. Create a dataset to save the results

In [19]:
results = pd.DataFrame(columns = ['model','accuracy','precision','recall','f1'])
results

Empty DataFrame
Columns: [model, accuracy, precision, recall, f1]
Index: []

## 4. Train and evaluate Random Forest Classifier

In [20]:
rf_results = train_evaluate_model('RF', x_train, y_train, x_test, y_test)
results = pd.concat([results, rf_results], ignore_index=True)
rf_results

[Parallel(n_jobs=3)]: Using backend ThreadingBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done  44 tasks      | elapsed:    0.0s
[Parallel(n_jobs=3)]: Done 100 out of 100 | elapsed:    0.0s finished
[Parallel(n_jobs=3)]: Using backend ThreadingBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done  44 tasks      | elapsed:    0.0s
[Parallel(n_jobs=3)]: Done 100 out of 100 | elapsed:    0.0s finished

  model  accuracy  precision  recall      f1
0    RF     0.875      0.875   0.875  0.8733

## 5. Train and Evaluate KNeighbors Classifier

In [21]:
knn_results = train_evaluate_model('KNN', x_train, y_train, x_test, y_test)
results = pd.concat([results, knn_results], ignore_index=True)
knn_results

  model  accuracy  precision  recall     f1
0   KNN    0.7083     0.7396  0.7083  0.713

## 6. Train and evaluate Decision Tree Classifier

In [22]:
dt_results = train_evaluate_model('DT', x_train, y_train, x_test, y_test)
results = pd.concat([results, dt_results], ignore_index=True)
dt_results

  model  accuracy  precision  recall      f1
0    DT      0.75     0.7675    0.75  0.7536

## 7. Train and evaluate Support Vector Machines Classifier

In [23]:
svm_results = train_evaluate_model('SVM', x_train, y_train, x_test, y_test)
results = pd.concat([results, svm_results], ignore_index=True)
svm_results

[LibSVM].*..WARN: libsvm Solver reached max_iter
optimization finished, #iter = 300
obj = -2.082230, rho = -1.976510
nSV = 21, nBSV = 0
Total nSV = 21
.*..*
optimization finished, #iter = 242
obj = -0.910218, rho = -1.443532
nSV = 18, nBSV = 0
Total nSV = 18
.*.*
optimization finished, #iter = 177
obj = -1.679250, rho = -1.209365
nSV = 17, nBSV = 0
Total nSV = 17
.*..WARN: libsvm Solver reached max_iter
optimization finished, #iter = 300
obj = -1.689613, rho = -1.661667
nSV = 21, nBSV = 0
Total nSV = 21
*.*
optimization finished, #iter = 82
obj = -1.648974, rho = -1.257650
nSV = 16, nBSV = 0
Total nSV = 16
..*.WARN: libsvm Solver reached max_iter
optimization finished, #iter = 300
obj = -2.307018, rho = 1.930405
nSV = 19, nBSV = 0
Total nSV = 19

  model  accuracy  precision  recall      f1
0   SVM    0.8333     0.8333  0.8333  0.8333

## 8. Train and evaluate Multilayer Perceptron Classifier

In [24]:
mlp_results = train_evaluate_model('MLP', x_train, y_train, x_test, y_test)
results = pd.concat([results, mlp_results], ignore_index=True)
mlp_results

Iteration 1, loss = 0.66610466
Iteration 2, loss = 0.62322875
Iteration 3, loss = 0.58494687
Iteration 4, loss = 0.54971144
Iteration 5, loss = 0.51731746
Iteration 6, loss = 0.48711655
Iteration 7, loss = 0.45839319
Iteration 8, loss = 0.43120199
Iteration 9, loss = 0.40454136
Iteration 10, loss = 0.37837681
Iteration 11, loss = 0.35266155
Iteration 12, loss = 0.32754705
Iteration 13, loss = 0.30301905
Iteration 14, loss = 0.27941834
Iteration 15, loss = 0.25680149
Iteration 16, loss = 0.23509953
Iteration 17, loss = 0.21448511
Iteration 18, loss = 0.19521520
Iteration 19, loss = 0.17732216
Iteration 20, loss = 0.16083899
Iteration 21, loss = 0.14582052
Iteration 22, loss = 0.13221271
Iteration 23, loss = 0.11999645
Iteration 24, loss = 0.10907209
Iteration 25, loss = 0.09934414
Iteration 26, loss = 0.09071843
Iteration 27, loss = 0.08312408
Iteration 28, loss = 0.07643747
Iteration 29, loss = 0.07051671
Iteration 30, loss = 0.06527613
Iteration 31, loss = 0.06069489
Iteration 32, loss = 0.05666272
Iteration 33, loss = 0.05304428
Iteration 34, loss = 0.04964258
Iteration 35, loss = 0.04649123
Iteration 36, loss = 0.04356445
Iteration 37, loss = 0.04085987
Iteration 38, loss = 0.03829837
Iteration 39, loss = 0.03585720
Iteration 40, loss = 0.03352409
Iteration 41, loss = 0.03117786
Iteration 42, loss = 0.02882207
Iteration 43, loss = 0.02658523
Iteration 44, loss = 0.02445789
Iteration 45, loss = 0.02243452
Iteration 46, loss = 0.02058014
Iteration 47, loss = 0.01892377
Iteration 48, loss = 0.01740672
Iteration 49, loss = 0.01601852
Iteration 50, loss = 0.01473489
Iteration 51, loss = 0.01354813
Iteration 52, loss = 0.01243684
Iteration 53, loss = 0.01141573
Iteration 54, loss = 0.01048076
Iteration 55, loss = 0.00964106
Iteration 56, loss = 0.00888318
Iteration 57, loss = 0.00821044
Iteration 58, loss = 0.00762562
Iteration 59, loss = 0.00710884
Iteration 60, loss = 0.00665546
Iteration 61, loss = 0.00625313
Iteration 62, loss = 0.00588970
Iteration 63, loss = 0.00556002
Iteration 64, loss = 0.00525664
Iteration 65, loss = 0.00497232
Iteration 66, loss = 0.00470648
Iteration 67, loss = 0.00445669
Iteration 68, loss = 0.00422438
Iteration 69, loss = 0.00400695
Iteration 70, loss = 0.00380399
Iteration 71, loss = 0.00361543
Iteration 72, loss = 0.00344124
Iteration 73, loss = 0.00328131
Iteration 74, loss = 0.00313391
Iteration 75, loss = 0.00299826
Iteration 76, loss = 0.00287323
Iteration 77, loss = 0.00275787
Iteration 78, loss = 0.00265169
Iteration 79, loss = 0.00255316
Iteration 80, loss = 0.00246188
Iteration 81, loss = 0.00237668
Iteration 82, loss = 0.00229619
Iteration 83, loss = 0.00222036
Iteration 84, loss = 0.00214872
Iteration 85, loss = 0.00208083
Iteration 86, loss = 0.00201643
Iteration 87, loss = 0.00195564
Iteration 88, loss = 0.00189841
Iteration 89, loss = 0.00184424
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.

  model  accuracy  precision  recall      f1
0   MLP    0.8333     0.8333  0.8333  0.8333

## 9. Save results file

In [25]:
results.to_csv('RESULTS/models_results_sdv.csv', index=False)
results

  model  accuracy  precision  recall      f1
0    RF    0.8750     0.8750  0.8750  0.8733
1   KNN    0.7083     0.7396  0.7083  0.7130
2    DT    0.7500     0.7675  0.7500  0.7536
3   SVM    0.8333     0.8333  0.8333  0.8333
4   MLP    0.8333     0.8333  0.8333  0.8333