# TSTR WGANGP Dataset 0 - REMBRANDT

In [12]:
#import libraries
import warnings
warnings.filterwarnings("ignore")
import numpy as np
import pandas as pd
import os
print('Libraries imported!!')

Libraries imported!!

In [13]:
#define directory of functions and actual directory
FUNCTIONS_HOME = '../../../functions/evaluation_functions/' #home directory of the project
REAL_DATA_HOME = '../../../data/raw/rembrandt/' #home directory of the project
SYN_DATA_HOME  = '../../../data/processed/rembrandt/' #home directory of the project
FUNCTIONS_DIR = 'EVALUATION FUNCTIONS/UTILITY'
ACTUAL_DIR = os.getcwd()

#change directory to functions directory
os.chdir(FUNCTIONS_HOME + FUNCTIONS_DIR)

#import functions for data labelling analisys
from utility_evaluation import DataPreProcessor
from utility_evaluation import train_evaluate_model

#change directory to actual directory
os.chdir(ACTUAL_DIR)
print('Functions imported!!')

Functions imported!!

## 1. Read data

In [14]:
#read real dataset
train_data = pd.read_csv(SYN_DATA_HOME + '0_Depression_Data_Synthetic_WGANGP.csv')
categorical_columns = ['group']
for col in categorical_columns :
    train_data[col] = train_data[col].astype('category')
train_data

,group,ma1,hars1,ma2,hars2,ma3,hars3,ma4,hars4,ma5,...,ma10,hars10,ma11,hars11,ma12,hars12,ma13,hars13,ma14,hars14
0,Remitted,-0.232431,-0.641733,-0.539639,-0.470065,0.029859,-0.527941,0.049921,-0.008577,0.345985,...,-0.016773,0.509466,0.312602,-0.457250,-1.345626,-0.939853,-0.211576,-1.060308,-0.201716,0.059329
1,Remitted,-0.438878,-0.647915,-0.697470,-0.612660,-0.198501,-0.807232,-0.472897,-0.760770,0.203592,...,-0.549383,-0.253486,-0.140256,-1.536836,-1.349750,-0.902550,-0.573828,-1.175591,-0.366443,-0.228567
2,Remitted,-0.485129,-0.902398,-0.664433,-0.903242,-0.359741,-0.927780,-0.453517,-0.636809,-0.432897,...,-0.268322,-0.160915,-0.603181,-1.274843,-1.289971,-1.095800,-0.482784,-0.939701,-0.353121,-0.367287
3,Remitted,-0.448292,-0.728121,-0.671050,-0.906145,-0.170006,-0.903799,-0.398556,-0.612038,-0.153520,...,-0.519650,-0.236944,-0.005361,-1.375591,-1.399358,-0.945524,-0.490271,-1.077238,-0.433430,-0.395891
4,Remitted,-0.203852,-0.372626,-0.511113,-0.280794,0.586791,-0.038579,0.310158,0.008070,1.263885,...,0.491446,1.020091,1.365010,-0.238089,-1.095931,-0.380461,0.130997,-0.772844,-0.077605,-0.103894
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,Remitted,-0.543728,-0.976481,-0.673136,-0.881550,-0.395340,-0.994449,-0.455872,-0.754611,-0.391495,...,-0.243153,-0.211814,-0.346020,-0.891443,-1.089043,-1.284493,-0.493113,-0.959523,-0.489418,-0.348733
92,Remitted,-0.383145,-0.759394,-0.645635,-0.593219,-0.408321,-0.996203,-0.531804,-0.809110,-0.280039,...,-0.443150,-0.354375,-0.138610,-1.719289,-1.159131,-0.926809,-0.453729,-1.044289,-0.513161,-0.283952
93,Remitted,-0.347744,-0.875085,-0.591221,-0.503691,-0.207976,-0.940429,-0.115871,-0.494790,-0.147658,...,-0.348015,-0.104458,-0.022799,-1.586994,-1.327833,-0.791115,-0.148742,-0.894716,-0.322232,-0.198763
94,Remitted,-0.374976,-0.783334,-0.594523,-0.710815,-0.398791,-0.904194,-0.223756,-0.601731,-0.190100,...,-0.373568,-0.022735,-0.304128,-1.276140,-1.276421,-1.111982,-0.404459,-1.021739,-0.368046,-0.192600
95,Remitted,-0.452465,-0.776700,-0.621964,-0.920384,-0.191526,-1.089751,-0.261620,-0.672839,-0.352135,...,-0.170332,-0.267616,-0.434490,-1.187475,-1.555719,-1.083942,-0.314781,-0.934308,-0.515529,-0.374878

In [15]:
#read test data
test_data = pd.read_csv(REAL_DATA_HOME + '0_Depression_Data_Real_Test.csv')
for col in categorical_columns :
    test_data[col] = test_data[col].astype('category')
test_data

,group,ma1,hars1,ma2,hars2,ma3,hars3,ma4,hars4,ma5,...,ma10,hars10,ma11,hars11,ma12,hars12,ma13,hars13,ma14,hars14
0,Remitted,-0.309550,-0.569420,-0.872369,-0.756370,-0.497156,-0.008569,-0.684762,0.178382,-0.121944,...,0.065662,-0.008569,1.566511,-0.008569,0.440874,-0.569420,-0.309550,0.178382,-0.121944,0.178382
1,Remitted,0.065662,0.178382,-0.309550,-0.569420,-0.497156,-0.382469,0.253268,-0.195519,-0.497156,...,-0.497156,-0.382469,-0.497156,-0.756370,-0.684762,-0.382469,-0.872369,-0.195519,-0.309550,0.739233
2,Remitted,-0.684762,-0.943320,-0.309550,-0.569420,-0.497156,-0.943320,-0.121944,-0.756370,-0.497156,...,-0.872369,-0.382469,-0.309550,-0.195519,-0.121944,-0.382469,-0.309550,-0.569420,-0.497156,-0.382469
3,Remitted,0.440874,-0.195519,1.003693,0.552282,0.440874,-0.569420,0.440874,-0.569420,-0.121944,...,0.440874,0.365332,-0.684762,-0.756370,0.065662,-0.008569,-0.497156,-0.195519,-0.121944,-0.008569
4,Remitted,1.003693,0.365332,-0.309550,-0.756370,2.879754,2.982637,0.816087,-0.195519,0.065662,...,-0.497156,-0.569420,-0.684762,-0.569420,0.065662,-0.943320,-0.309550,-0.569420,0.628481,0.365332
5,Remitted,0.440874,0.178382,-0.309550,-0.569420,0.628481,-0.382469,1.191299,0.739233,0.065662,...,-0.872369,-0.195519,-0.684762,-0.195519,-0.121944,0.552282,-0.872369,-0.382469,-0.497156,-0.382469
6,Remitted,-0.684762,0.365332,0.816087,0.739233,-0.309550,0.365332,0.816087,1.300084,0.253268,...,-0.309550,0.178382,-0.121944,0.739233,0.065662,-0.008569,-0.121944,-0.569420,-0.309550,1.113133
7,Remitted,-0.309550,-0.569420,-0.121944,-0.569420,-0.872369,-0.756370,-0.684762,-0.569420,-0.872369,...,-0.497156,-0.569420,-0.872369,-1.130271,-0.497156,-0.569420,-0.872369,-0.756370,0.065662,-0.008569
8,Remitted,0.628481,-0.382469,-0.309550,-0.569420,-0.497156,-0.569420,0.816087,-0.943320,1.941724,...,3.817785,1.860935,-0.872369,-0.569420,-0.684762,-1.130271,-0.309550,-1.130271,0.440874,0.552282
9,Control,-0.872369,-1.130271,-0.872369,-0.569420,-0.684762,-0.943320,-0.497156,-0.756370,-0.872369,...,-0.872369,-1.130271,-0.872369,-1.130271,-0.872369,-1.130271,-0.872369,-0.943320,-0.684762,0.178382
10,Remitted,-0.309550,-0.382469,0.065662,0.365332,2.129330,0.926183,3.817785,0.739233,4.005391,...,3.067360,1.860935,3.254966,2.234835,0.628481,0.178382,0.253268,0.552282,0.065662,1.113133
11,Control,-0.309550,-0.382469,-0.309550,0.739233,-0.121944,0.739233,0.253268,0.739233,-0.121944,...,0.065662,0.739233,-0.684762,0.178382,1.003693,1.860935,-0.872369,-0.943320,-0.121944,1.113133
12,Control,-0.684762,-0.943320,-0.872369,-0.943320,-0.872369,-1.130271,-0.497156,-0.569420,-0.872369,...,-0.684762,-1.130271,-0.872369,-0.943320,-0.872369,-0.943320,-0.872369,-0.943320,-0.872369,-0.569420
13,Control,-0.872369,-1.130271,-0.872369,-0.756370,-0.684762,-0.943320,-0.684762,-0.569420,-0.872369,...,-0.872369,-1.130271,-0.684762,-0.382469,-0.497156,-0.382469,-0.872369,-0.569420,-0.872369,-1.130271
14,Control,-0.872369,-0.943320,-0.872369,0.178382,-0.872369,-1.130271,-0.497156,-0.756370,-0.121944,...,-0.309550,-0.569420,-0.121944,-0.008569,-0.497156,-0.195519,-0.684762,-0.382469,-0.872369,-1.130271
15,Control,-0.872369,-0.569420,-0.872369,-0.569420,-0.309550,-0.943320,-0.684762,-0.943320,-0.684762,...,-0.497156,-0.756370,-0.684762,-0.943320,-0.684762,-1.130271,-0.872369,-0.943320,-0.684762,0.365332
16,Remitted,-0.497156,-0.943320,0.440874,1.113133,0.816087,0.365332,2.879754,1.300084,1.003693,...,-0.497156,-0.569420,-0.684762,-0.756370,-0.684762,-1.130271,-0.309550,-0.756370,-0.309550,0.926183
17,Remitted,-0.309550,-0.382469,-0.309550,-0.569420,-0.497156,-0.382469,-0.684762,-0.943320,1.191299,...,-0.497156,-0.569420,-0.684762,-1.130271,-0.684762,-1.130271,-0.684762,-0.943320,0.065662,0.552282
18,Remitted,-0.309550,-0.382469,0.253268,-0.195519,-0.497156,-0.943320,0.253268,-0.008569,-0.121944,...,-0.684762,-0.756370,-0.684762,-0.943320,-0.497156,-0.569420,-0.309550,-0.569420,-0.497156,-0.569420
19,Control,-0.684762,-0.943320,-0.684762,-0.569420,-0.121944,-0.569420,-0.497156,-0.382469,-0.497156,...,-0.497156,-0.382469,-0.684762,-0.756370,-0.872369,-0.756370,-0.497156,-0.756370,-0.684762,-0.382469
20,Control,0.253268,0.178382,0.253268,1.113133,-0.309550,-0.756370,-0.121944,-0.008569,-0.121944,...,-0.309550,0.552282,-0.121944,0.178382,-0.309550,0.739233,-0.121944,0.739233,0.065662,0.365332
21,Remitted,-0.121944,0.178382,-0.121944,-0.008569,1.003693,0.178382,3.254966,1.860935,1.003693,...,0.628481,-0.382469,0.628481,1.860935,2.129330,1.487034,4.005391,2.982637,2.504542,2.047885
22,Control,-0.684762,-0.943320,-0.872369,-0.756370,-0.872369,-1.130271,-0.872369,-1.130271,-0.872369,...,-0.684762,-0.756370,-0.684762,-0.943320,-0.684762,-0.943320,-0.872369,-1.130271,-0.497156,0.365332
23,Remitted,0.253268,-0.008569,1.003693,3.543488,3.254966,3.917388,2.504542,5.039090,1.003693,...,-0.497156,-0.569420,-0.684762,-0.943320,0.065662,-0.195519,0.816087,0.365332,-0.121944,1.300084

In [17]:
target = 'group'
#quick look at the breakdown of class values
print('Train data')
print(train_data.shape)
print(train_data.groupby(target).size())
print('#####################################')
print('Test data')
print(test_data.shape)
print(test_data.groupby(target).size())

Train data
(96, 29)
group
Remitted    96
dtype: int64
#####################################
Test data
(24, 29)
group
Control      9
Remitted    15
dtype: int64

## 2. Pre-process training data

In [28]:
target = 'group'
categorical_columns = []
numerical_columns = train_data.select_dtypes(include=['int64','float64']).columns.tolist()
categories = [np.array(range(2))] if categorical_columns else []
data_preprocessor = DataPreProcessor(categorical_columns, numerical_columns, categories)
x_train = data_preprocessor.preprocess_train_data(train_data.loc[:, train_data.columns != target])
y_train = train_data.loc[:, target]

x_train.shape, y_train.shape

((96, 28), (96,))

## 3. Preprocess test data

In [29]:
x_test = data_preprocessor.preprocess_test_data(test_data.loc[:, test_data.columns != target])
y_test = test_data.loc[:, target]
x_test.shape, y_test.shape

((24, 28), (24,))

## 4. Create a dataset to save the results

In [20]:
results = pd.DataFrame(columns = ['model','accuracy','precision','recall','f1'])
results

Empty DataFrame
Columns: [model, accuracy, precision, recall, f1]
Index: []

## 4. Train and evaluate Random Forest Classifier

In [21]:
rf_results = train_evaluate_model('RF', x_train, y_train, x_test, y_test)
results = pd.concat([results, rf_results], ignore_index=True)
rf_results

[Parallel(n_jobs=3)]: Using backend ThreadingBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done  44 tasks      | elapsed:    0.0s
[Parallel(n_jobs=3)]: Done 100 out of 100 | elapsed:    0.1s finished
[Parallel(n_jobs=3)]: Using backend ThreadingBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done  44 tasks      | elapsed:    0.0s
[Parallel(n_jobs=3)]: Done 100 out of 100 | elapsed:    0.0s finished

  model  accuracy  precision  recall      f1
0    RF     0.625     0.3906   0.625  0.4808

## 5. Train and Evaluate KNeighbors Classifier

In [22]:
knn_results = train_evaluate_model('KNN', x_train, y_train, x_test, y_test)
results = pd.concat([results, knn_results], ignore_index=True)
knn_results

  model  accuracy  precision  recall      f1
0   KNN     0.625     0.3906   0.625  0.4808

## 6. Train and evaluate Decision Tree Classifier

In [23]:
dt_results = train_evaluate_model('DT', x_train, y_train, x_test, y_test)
results = pd.concat([results, dt_results], ignore_index=True)
dt_results

  model  accuracy  precision  recall      f1
0    DT     0.625     0.3906   0.625  0.4808

## 7. Train and evaluate Support Vector Machines Classifier

In [30]:
svm_results = train_evaluate_model('SVM', x_train, y_train, x_test, y_test)
svm_results['model'] = svm_results['model'].replace(['MLP'],'SVM')
results = pd.concat([results, svm_results], ignore_index=True)
svm_results

ValueError: The number of classes has to be greater than one; got 1 class

## 8. Train and evaluate Multilayer Perceptron Classifier

In [ ]:
mlp_results = train_evaluate_model('MLP', x_train, y_train, x_test, y_test)
results = pd.concat([results, mlp_results], ignore_index=True)
mlp_results

## 9. Save results file

In [ ]:
results.to_csv('RESULTS/models_results_wgangp.csv', index=False)
results