# TRTR Dataset A - Diabetes

In [1]:
#import libraries
import warnings
warnings.filterwarnings("ignore")
import numpy as np
import pandas as pd
import os
print('Libraries imported!!')

Libraries imported!!

In [2]:
#define directory of functions and actual directory
FUNCTIONS_HOME = '../../../functions/evaluation_functions/' #home directory of the project
REAL_DATA_HOME = '../../../data/raw/chap/' #home directory of the project
SYN_DATA_HOME  = '../../../data/processed/chap/' #home directory of the project
FUNCTIONS_DIR = 'EVALUATION FUNCTIONS/UTILITY'
ACTUAL_DIR = os.getcwd()

#change directory to functions directory
os.chdir(FUNCTIONS_HOME + FUNCTIONS_DIR)
#import functions for data labelling analisys
from utility_evaluation import DataPreProcessor
from utility_evaluation import train_evaluate_model

#change directory to actual directory
os.chdir(ACTUAL_DIR)
print('Functions imported!!')

Functions imported!!

## 1. Read data

In [3]:
#read real dataset
train_data = pd.read_csv(REAL_DATA_HOME + '1_Chap_Data_Real_Train.csv')
categorical_columns = ['group']
for col in categorical_columns :
    train_data[col] = train_data[col].astype('category')
train_data

,group,sbp1,sbp2,sbp3,sbp4,dbp1,dbp2,dbp3,dbp4
0,Group0,2.009493,0.084640,-0.020160,0.107037,0.857051,-0.048580,0.141517,0.137274
1,Group0,1.647881,0.285048,0.750705,-0.365256,0.594206,-0.094862,0.201428,-0.240859
2,Group0,0.045838,-0.301003,-0.007641,0.189160,1.875668,-0.152879,0.003445,0.012916
3,Group0,-1.626382,0.438629,-0.352224,-0.147169,-2.445341,0.362086,-0.132354,-0.016382
4,Group0,-0.244556,-0.781058,0.191160,0.637441,-2.766078,-1.110363,0.746589,0.140332
...,...,...,...,...,...,...,...,...,...
2712,Group0,0.048656,0.340805,0.146978,-0.077990,1.468295,-0.105885,0.037067,-0.001841
2713,Group0,-3.007362,-0.110868,-0.547719,-0.061449,-3.286850,-0.079093,-0.126217,0.165070
2714,Group0,0.481546,-0.118290,-0.159216,-0.046665,0.013795,0.235801,-0.128855,0.206748
2715,Group0,0.199530,0.371273,0.268324,0.670192,0.275167,-0.382674,0.076358,0.294886
2716,Group0,3.319253,0.852148,-1.115749,-0.142213,4.733011,1.221218,-0.466025,-0.221787

In [4]:
#read test data
test_data = pd.read_csv(REAL_DATA_HOME + '1_Chap_Data_Real_Test.csv')
for col in categorical_columns :
    test_data[col] = test_data[col].astype('category')
test_data

,group,sbp1,sbp2,sbp3,sbp4,dbp1,dbp2,dbp3,dbp4
0,Group0,-3.053475,-0.177497,-0.010661,0.205118,-2.773102,-0.653440,0.319585,0.017457
1,Group0,-1.375254,0.761393,0.270692,0.140597,-2.157208,-0.297755,0.126143,0.118270
2,Group0,3.681521,1.147414,-0.119372,0.276912,1.452468,0.068735,0.043671,0.074436
3,Group0,0.383070,0.211771,0.374537,0.254718,5.352641,-0.611636,0.344336,0.044627
4,Group0,2.009235,0.765321,0.100557,0.058659,2.842860,0.980271,-0.014527,0.096506
...,...,...,...,...,...,...,...,...,...
674,Group0,1.185955,-0.248240,-0.258972,0.284599,0.816753,0.553623,-0.456024,0.157975
675,Group0,-4.898967,-0.576216,-0.150236,0.069086,-4.450551,-0.192307,0.034382,-0.174072
676,Group0,-3.339095,0.856460,-1.021265,-0.131611,0.639099,0.783467,-0.128578,-0.067689
677,Group0,-3.844234,0.083773,0.334898,-0.210940,-1.259774,0.726944,-0.299066,-0.123455
678,Group0,-7.783068,-0.616220,0.063062,-0.287367,-6.210207,-1.128977,0.308871,-0.170048

In [5]:
target = 'group'
#quick look at the breakdown of class values
print('Train data')
print(train_data.shape)
print(train_data.groupby(target).size())
print('#####################################')
print('Test data')
print(test_data.shape)
print(test_data.groupby(target).size())

Train data
(2717, 9)
group
Group0    2606
Group1     111
dtype: int64
#####################################
Test data
(679, 9)
group
Group0    645
Group1     34
dtype: int64

## 2. Pre-process training data

In [6]:
target = 'group'

# 先分离特征和目标
X = train_data.drop(columns=[target])
y = train_data[target]

# 然后基于 X 定义列
categorical_columns = X.select_dtypes(include=['object', 'category']).columns.tolist()
numerical_columns = X.select_dtypes(include=['int64', 'float64']).columns.tolist()

# categories 需要根据你的实际分类列调整
categories = [np.array(range(2))] if categorical_columns else []

data_preprocessor = DataPreProcessor(categorical_columns, numerical_columns, categories)
x_train = data_preprocessor.preprocess_train_data(X)
y_train = y

x_train.shape, y_train.shape

((2717, 8), (2717,))

## 3. Preprocess test data

In [7]:
x_test = data_preprocessor.preprocess_test_data(test_data.loc[:, test_data.columns != target])
y_test = test_data.loc[:, target]
x_test.shape, y_test.shape

((679, 8), (679,))

## 4. Create a dataset to save the results

In [8]:
results = pd.DataFrame(columns = ['model','accuracy','precision','recall','f1'])
results

Empty DataFrame
Columns: [model, accuracy, precision, recall, f1]
Index: []

## 4. Train and evaluate Random Forest Classifier

In [9]:
rf_results = train_evaluate_model('RF', x_train, y_train, x_test, y_test)
results = pd.concat([results, rf_results], ignore_index=True)
rf_results

[Parallel(n_jobs=3)]: Using backend ThreadingBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done  44 tasks      | elapsed:    0.1s
[Parallel(n_jobs=3)]: Done 100 out of 100 | elapsed:    0.1s finished
[Parallel(n_jobs=3)]: Using backend ThreadingBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done  44 tasks      | elapsed:    0.0s
[Parallel(n_jobs=3)]: Done 100 out of 100 | elapsed:    0.0s finished

  model  accuracy  precision  recall      f1
0    RF    0.9558     0.9478  0.9558  0.9426

## 5. Train and Evaluate KNeighbors Classifier

In [10]:
knn_results = train_evaluate_model('KNN', x_train, y_train, x_test, y_test)
results = pd.concat([results, knn_results], ignore_index=True)
knn_results

  model  accuracy  precision  recall      f1
0   KNN    0.9485     0.9202  0.9485  0.9275

## 6. Train and evaluate Decision Tree Classifier

In [11]:
dt_results = train_evaluate_model('DT', x_train, y_train, x_test, y_test)
results = pd.concat([results, dt_results], ignore_index=True)
dt_results

  model  accuracy  precision  recall      f1
0    DT    0.9234     0.9234  0.9234  0.9234

## 7. Train and evaluate Support Vector Machines Classifier

In [12]:
svm_results = train_evaluate_model('SVM', x_train, y_train, x_test, y_test)
results = pd.concat([results, svm_results], ignore_index=True)
svm_results

[LibSVM]WARN: libsvm Solver reached max_iter
optimization finished, #iter = 300
obj = -562.956779, rho = 0.778622
nSV = 156, nBSV = 0
Total nSV = 156
WARN: libsvm Solver reached max_iter
optimization finished, #iter = 300
obj = -706.155908, rho = 1.555257
nSV = 166, nBSV = 0
Total nSV = 166
WARN: libsvm Solver reached max_iter
optimization finished, #iter = 300
obj = -737.122458, rho = 0.736143
nSV = 161, nBSV = 0
Total nSV = 161
WARN: libsvm Solver reached max_iter
optimization finished, #iter = 300
obj = -804.430488, rho = 1.186184
nSV = 149, nBSV = 1
Total nSV = 149
WARN: libsvm Solver reached max_iter
optimization finished, #iter = 300
obj = -652.910070, rho = 1.590597
nSV = 176, nBSV = 0
Total nSV = 176
WARN: libsvm Solver reached max_iter
optimization finished, #iter = 300
obj = -189.818454, rho = -0.383538
nSV = 124, nBSV = 0
Total nSV = 124

  model  accuracy  precision  recall      f1
0   SVM    0.6627     0.9286  0.6627  0.7575

## 8. Train and evaluate Multilayer Perceptron Classifier

In [13]:
mlp_results = train_evaluate_model('MLP', x_train, y_train, x_test, y_test)
results = pd.concat([results, mlp_results], ignore_index=True)
mlp_results

Iteration 1, loss = 0.54521211
Iteration 2, loss = 0.27829981
Iteration 3, loss = 0.18840587
Iteration 4, loss = 0.16639010
Iteration 5, loss = 0.15065750
Iteration 6, loss = 0.14319027
Iteration 7, loss = 0.13687124
Iteration 8, loss = 0.13171297
Iteration 9, loss = 0.12695852
Iteration 10, loss = 0.12218133
Iteration 11, loss = 0.11909902
Iteration 12, loss = 0.11523355
Iteration 13, loss = 0.11238482
Iteration 14, loss = 0.11028170
Iteration 15, loss = 0.10794167
Iteration 16, loss = 0.10625930
Iteration 17, loss = 0.10442823
Iteration 18, loss = 0.10323876
Iteration 19, loss = 0.10257910
Iteration 20, loss = 0.10183838
Iteration 21, loss = 0.09974436
Iteration 22, loss = 0.09870070
Iteration 23, loss = 0.09803130
Iteration 24, loss = 0.09805747
Iteration 25, loss = 0.09730066
Iteration 26, loss = 0.09562086
Iteration 27, loss = 0.09368057
Iteration 28, loss = 0.09282467
Iteration 29, loss = 0.09794524
Iteration 30, loss = 0.09479793
Iteration 31, loss = 0.09198375
Iteration 32, loss = 0.08962028
Iteration 33, loss = 0.08863585
Iteration 34, loss = 0.08752702
Iteration 35, loss = 0.08588133
Iteration 36, loss = 0.08537911
Iteration 37, loss = 0.08490734
Iteration 38, loss = 0.08347068
Iteration 39, loss = 0.08284352
Iteration 40, loss = 0.08243226
Iteration 41, loss = 0.08091345
Iteration 42, loss = 0.07985720
Iteration 43, loss = 0.07977179
Iteration 44, loss = 0.07842717
Iteration 45, loss = 0.07680037
Iteration 46, loss = 0.07528590
Iteration 47, loss = 0.07420266
Iteration 48, loss = 0.07343825
Iteration 49, loss = 0.07220871
Iteration 50, loss = 0.07107866
Iteration 51, loss = 0.07166355
Iteration 52, loss = 0.06807536
Iteration 53, loss = 0.06778099
Iteration 54, loss = 0.06844005
Iteration 55, loss = 0.06762021
Iteration 56, loss = 0.06744123
Iteration 57, loss = 0.06675481
Iteration 58, loss = 0.06451771
Iteration 59, loss = 0.06171862
Iteration 60, loss = 0.05999906
Iteration 61, loss = 0.06321843
Iteration 62, loss = 0.05835117
Iteration 63, loss = 0.05699766
Iteration 64, loss = 0.05709045
Iteration 65, loss = 0.05732141
Iteration 66, loss = 0.05517354
Iteration 67, loss = 0.05387318
Iteration 68, loss = 0.05663528
Iteration 69, loss = 0.05221496
Iteration 70, loss = 0.05153773
Iteration 71, loss = 0.04946843
Iteration 72, loss = 0.04715741
Iteration 73, loss = 0.04715371
Iteration 74, loss = 0.05089870
Iteration 75, loss = 0.04745197
Iteration 76, loss = 0.04430689
Iteration 77, loss = 0.04471381
Iteration 78, loss = 0.04339784
Iteration 79, loss = 0.04277580
Iteration 80, loss = 0.04395974
Iteration 81, loss = 0.04314395
Iteration 82, loss = 0.04170917
Iteration 83, loss = 0.03728316
Iteration 84, loss = 0.03553736
Iteration 85, loss = 0.03504658
Iteration 86, loss = 0.03531403
Iteration 87, loss = 0.03404824
Iteration 88, loss = 0.03594755
Iteration 89, loss = 0.03597575
Iteration 90, loss = 0.03350415
Iteration 91, loss = 0.03092792
Iteration 92, loss = 0.03038737
Iteration 93, loss = 0.03360357
Iteration 94, loss = 0.03043824
Iteration 95, loss = 0.02886303
Iteration 96, loss = 0.02815436
Iteration 97, loss = 0.02735699
Iteration 98, loss = 0.02576180
Iteration 99, loss = 0.02540113
Iteration 100, loss = 0.02527507
Iteration 101, loss = 0.02516624
Iteration 102, loss = 0.02281278
Iteration 103, loss = 0.02225550
Iteration 104, loss = 0.02186294
Iteration 105, loss = 0.02179713
Iteration 106, loss = 0.02037499
Iteration 107, loss = 0.02159638
Iteration 108, loss = 0.01934201
Iteration 109, loss = 0.02003115
Iteration 110, loss = 0.02072901
Iteration 111, loss = 0.02106289
Iteration 112, loss = 0.01715398
Iteration 113, loss = 0.01599376
Iteration 114, loss = 0.01483685
Iteration 115, loss = 0.01570700
Iteration 116, loss = 0.01475228
Iteration 117, loss = 0.01338024
Iteration 118, loss = 0.01258733
Iteration 119, loss = 0.01631371
Iteration 120, loss = 0.01369457
Iteration 121, loss = 0.01412525
Iteration 122, loss = 0.01395873
Iteration 123, loss = 0.01164224
Iteration 124, loss = 0.01154229
Iteration 125, loss = 0.01146556
Iteration 126, loss = 0.01078060
Iteration 127, loss = 0.01047391
Iteration 128, loss = 0.01069262
Iteration 129, loss = 0.00960564
Iteration 130, loss = 0.00899689
Iteration 131, loss = 0.00846494
Iteration 132, loss = 0.00759696
Iteration 133, loss = 0.00735878
Iteration 134, loss = 0.00738421
Iteration 135, loss = 0.00641553
Iteration 136, loss = 0.00638082
Iteration 137, loss = 0.00612340
Iteration 138, loss = 0.00637722
Iteration 139, loss = 0.00701902
Iteration 140, loss = 0.00608286
Iteration 141, loss = 0.00756371
Iteration 142, loss = 0.00573625
Iteration 143, loss = 0.00591019
Iteration 144, loss = 0.00583734
Iteration 145, loss = 0.00511479
Iteration 146, loss = 0.00727106
Iteration 147, loss = 0.00501472
Iteration 148, loss = 0.00485913
Iteration 149, loss = 0.00439055
Iteration 150, loss = 0.00356255
Iteration 151, loss = 0.00333973
Iteration 152, loss = 0.00323605
Iteration 153, loss = 0.00318389
Iteration 154, loss = 0.00335057
Iteration 155, loss = 0.00295522
Iteration 156, loss = 0.00279993
Iteration 157, loss = 0.00271017
Iteration 158, loss = 0.00261075
Iteration 159, loss = 0.00241384
Iteration 160, loss = 0.00239081
Iteration 161, loss = 0.00231412
Iteration 162, loss = 0.00235260
Iteration 163, loss = 0.00222962
Iteration 164, loss = 0.00213117
Iteration 165, loss = 0.00205657
Iteration 166, loss = 0.00209459
Iteration 167, loss = 0.00203244
Iteration 168, loss = 0.00190674
Iteration 169, loss = 0.00180369
Iteration 170, loss = 0.00179480
Iteration 171, loss = 0.00177418
Iteration 172, loss = 0.00179151
Iteration 173, loss = 0.00171016
Iteration 174, loss = 0.00165697
Iteration 175, loss = 0.00182283
Iteration 176, loss = 0.00157641
Iteration 177, loss = 0.00152702
Iteration 178, loss = 0.00142492
Iteration 179, loss = 0.00141170
Iteration 180, loss = 0.00142763
Iteration 181, loss = 0.00135869
Iteration 182, loss = 0.00133449
Iteration 183, loss = 0.00131414
Iteration 184, loss = 0.00128911
Iteration 185, loss = 0.00124385
Iteration 186, loss = 0.00123693
Iteration 187, loss = 0.00124171
Iteration 188, loss = 0.00119878
Iteration 189, loss = 0.00124765
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.

  model  accuracy  precision  recall      f1
0   MLP    0.9426     0.9333  0.9426  0.9373

## 9. Save results file

In [14]:
results.to_csv('RESULTS/models_results_real.csv', index=False)
results

  model  accuracy  precision  recall      f1
0    RF    0.9558     0.9478  0.9558  0.9426
1   KNN    0.9485     0.9202  0.9485  0.9275
2    DT    0.9234     0.9234  0.9234  0.9234
3   SVM    0.6627     0.9286  0.6627  0.7575
4   MLP    0.9426     0.9333  0.9426  0.9373