# TSTR CTGAN Dataset A - Diabetes

In [1]:
#import libraries
import warnings
warnings.filterwarnings("ignore")
import numpy as np
import pandas as pd
import os
print('Libraries imported!!')
# os.makedirs('RESULTS', exist_ok=True)

Libraries imported!!

In [2]:
#define directory of functions and actual directory
FUNCTIONS_HOME = '../../../functions/evaluation_functions/' #home directory of the project
REAL_DATA_HOME = '../../../data/raw/chap/' #home directory of the project
SYN_DATA_HOME  = '../../../data/processed/chap/' #home directory of the project
FUNCTIONS_DIR = 'EVALUATION FUNCTIONS/UTILITY'
ACTUAL_DIR = os.getcwd()

#change directory to functions directory
os.chdir(FUNCTIONS_HOME + FUNCTIONS_DIR)

#import functions for data labelling analisys
from utility_evaluation import DataPreProcessor
from utility_evaluation import train_evaluate_model

#change directory to actual directory
os.chdir(ACTUAL_DIR)
print('Functions imported!!')

Functions imported!!

## 1. Read data

In [3]:
#read real dataset
train_data = pd.read_csv(SYN_DATA_HOME + '1_Chap_Data_Synthetic_CTGAN.csv')
categorical_columns = ['group']
for col in categorical_columns :
    train_data[col] = train_data[col].astype('category')
train_data

,group,sbp1,sbp2,sbp3,sbp4,dbp1,dbp2,dbp3,dbp4
0,Group0,6.094322,-0.208446,0.416890,0.515579,-7.706072,-0.527509,0.166410,0.211860
1,Group0,2.291828,-0.762772,-0.112074,0.083636,0.846565,1.539027,-0.004124,0.277265
2,Group0,-5.112419,-0.377207,0.224469,0.505163,7.457264,-0.497955,-0.752442,0.063517
3,Group0,6.007161,-0.165590,-0.152581,0.389270,-4.636239,-0.214006,-0.530647,0.046882
4,Group0,1.082027,-1.209130,-0.070217,0.204933,1.570072,0.721873,0.099834,0.010630
...,...,...,...,...,...,...,...,...,...
2712,Group0,3.814451,0.190931,-0.282501,0.325604,-2.521737,-0.304934,-0.905134,-0.061680
2713,Group0,-1.059330,0.216962,-0.006728,0.091072,-5.399747,1.604053,-1.166298,-0.027417
2714,Group0,9.769922,0.944167,0.407352,0.002913,-4.778331,0.129506,0.001454,0.194900
2715,Group0,-4.384517,0.040398,-0.064242,0.055481,-5.280489,-0.847199,0.277913,0.162433
2716,Group1,-7.699921,-0.086799,-0.938739,0.373963,-10.346422,0.302718,-0.679478,0.292614

In [4]:
#read test data
test_data = pd.read_csv(REAL_DATA_HOME + '1_Chap_Data_Real_Test.csv')
for col in categorical_columns :
    test_data[col] = test_data[col].astype('category')
test_data

,group,sbp1,sbp2,sbp3,sbp4,dbp1,dbp2,dbp3,dbp4
0,Group0,-3.053475,-0.177497,-0.010661,0.205118,-2.773102,-0.653440,0.319585,0.017457
1,Group0,-1.375254,0.761393,0.270692,0.140597,-2.157208,-0.297755,0.126143,0.118270
2,Group0,3.681521,1.147414,-0.119372,0.276912,1.452468,0.068735,0.043671,0.074436
3,Group0,0.383070,0.211771,0.374537,0.254718,5.352641,-0.611636,0.344336,0.044627
4,Group0,2.009235,0.765321,0.100557,0.058659,2.842860,0.980271,-0.014527,0.096506
...,...,...,...,...,...,...,...,...,...
674,Group0,1.185955,-0.248240,-0.258972,0.284599,0.816753,0.553623,-0.456024,0.157975
675,Group0,-4.898967,-0.576216,-0.150236,0.069086,-4.450551,-0.192307,0.034382,-0.174072
676,Group0,-3.339095,0.856460,-1.021265,-0.131611,0.639099,0.783467,-0.128578,-0.067689
677,Group0,-3.844234,0.083773,0.334898,-0.210940,-1.259774,0.726944,-0.299066,-0.123455
678,Group0,-7.783068,-0.616220,0.063062,-0.287367,-6.210207,-1.128977,0.308871,-0.170048

In [5]:
target = 'group'
#quick look at the breakdown of class values
print('Train data')
print(train_data.shape)
# print(train_data.groupby(target).size())
print('#####################################')
print('Test data')
print(test_data.shape)
print(test_data.groupby(target).size())

Train data
(2717, 9)
#####################################
Test data
(679, 9)
group
Group0    645
Group1     34
dtype: int64

## 2. Pre-process training data

In [6]:
target = 'group'
categorical_columns = []
numerical_columns = train_data.select_dtypes(include=['int64','float64']).columns.tolist()
categories = [np.array(range(2))] if categorical_columns else []
data_preprocessor = DataPreProcessor(categorical_columns, numerical_columns, categories)
x_train = data_preprocessor.preprocess_train_data(train_data.loc[:, train_data.columns != target])
y_train = train_data.loc[:, target]

x_train.shape, y_train.shape

((2717, 8), (2717,))

## 3. Preprocess test data

In [7]:
x_test = data_preprocessor.preprocess_test_data(test_data.loc[:, test_data.columns != target])
y_test = test_data.loc[:, target]
x_test.shape, y_test.shape

((679, 8), (679,))

## 4. Create a dataset to save the results

In [8]:
results = pd.DataFrame(columns = ['model','accuracy','precision','recall','f1'])
results

Empty DataFrame
Columns: [model, accuracy, precision, recall, f1]
Index: []

## 4. Train and evaluate Random Forest Classifier

In [9]:
rf_results = train_evaluate_model('RF', x_train, y_train, x_test, y_test)
results = pd.concat([results, rf_results], ignore_index=True)
rf_results

[Parallel(n_jobs=3)]: Using backend ThreadingBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done  44 tasks      | elapsed:    0.1s
[Parallel(n_jobs=3)]: Done 100 out of 100 | elapsed:    0.1s finished
[Parallel(n_jobs=3)]: Using backend ThreadingBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done  44 tasks      | elapsed:    0.0s
[Parallel(n_jobs=3)]: Done 100 out of 100 | elapsed:    0.0s finished

  model  accuracy  precision  recall      f1
0    RF    0.9043     0.9457  0.9043  0.9207

## 5. Train and Evaluate KNeighbors Classifier

In [10]:
knn_results = train_evaluate_model('KNN', x_train, y_train, x_test, y_test)
results = pd.concat([results, knn_results], ignore_index=True)
knn_results

  model  accuracy  precision  recall      f1
0   KNN    0.9146      0.944  0.9146  0.9266

## 6. Train and evaluate Decision Tree Classifier

In [11]:
dt_results = train_evaluate_model('DT', x_train, y_train, x_test, y_test)
results = pd.concat([results, dt_results], ignore_index=True)
dt_results

  model  accuracy  precision  recall      f1
0    DT    0.8689     0.9414  0.8689  0.8975

## 7. Train and evaluate Support Vector Machines Classifier

In [12]:
svm_results = train_evaluate_model('SVM', x_train, y_train, x_test, y_test)
results = pd.concat([results, svm_results], ignore_index=True)
svm_results

[LibSVM]WARN: libsvm Solver reached max_iter
optimization finished, #iter = 300
obj = -526.970590, rho = 0.715104
nSV = 203, nBSV = 0
Total nSV = 203
WARN: libsvm Solver reached max_iter
optimization finished, #iter = 300
obj = -495.048645, rho = 0.043378
nSV = 217, nBSV = 0
Total nSV = 217
WARN: libsvm Solver reached max_iter
optimization finished, #iter = 300
obj = -487.298068, rho = 0.529119
nSV = 215, nBSV = 0
Total nSV = 215
WARN: libsvm Solver reached max_iter
optimization finished, #iter = 300
obj = -439.985243, rho = 0.197008
nSV = 238, nBSV = 0
Total nSV = 238
WARN: libsvm Solver reached max_iter
optimization finished, #iter = 300
obj = -456.088869, rho = 0.178670
nSV = 212, nBSV = 0
Total nSV = 212
WARN: libsvm Solver reached max_iter
optimization finished, #iter = 300
obj = -376.368904, rho = 0.064034
nSV = 214, nBSV = 0
Total nSV = 214

  model  accuracy  precision  recall      f1
0   SVM    0.7511     0.9394  0.7511  0.8204

## 8. Train and evaluate Multilayer Perceptron Classifier

In [13]:
mlp_results = train_evaluate_model('MLP', x_train, y_train, x_test, y_test)
results =pd.concat([results, mlp_results], ignore_index=True)
mlp_results

Iteration 1, loss = 0.63454400
Iteration 2, loss = 0.42127418
Iteration 3, loss = 0.25094303
Iteration 4, loss = 0.21312023
Iteration 5, loss = 0.20903565
Iteration 6, loss = 0.20454860
Iteration 7, loss = 0.20108483
Iteration 8, loss = 0.19905786
Iteration 9, loss = 0.19767279
Iteration 10, loss = 0.19582942
Iteration 11, loss = 0.19421170
Iteration 12, loss = 0.19163916
Iteration 13, loss = 0.19028252
Iteration 14, loss = 0.18938023
Iteration 15, loss = 0.19060224
Iteration 16, loss = 0.18865163
Iteration 17, loss = 0.18669260
Iteration 18, loss = 0.18358217
Iteration 19, loss = 0.18468438
Iteration 20, loss = 0.18448822
Iteration 21, loss = 0.18098251
Iteration 22, loss = 0.18266416
Iteration 23, loss = 0.18048336
Iteration 24, loss = 0.18007969
Iteration 25, loss = 0.17405755
Iteration 26, loss = 0.17354116
Iteration 27, loss = 0.17270955
Iteration 28, loss = 0.16986748
Iteration 29, loss = 0.17059264
Iteration 30, loss = 0.16911266
Iteration 31, loss = 0.16515180
Iteration 32, loss = 0.16407524
Iteration 33, loss = 0.16280548
Iteration 34, loss = 0.16004730
Iteration 35, loss = 0.16012105
Iteration 36, loss = 0.15685088
Iteration 37, loss = 0.15798256
Iteration 38, loss = 0.15395728
Iteration 39, loss = 0.15022258
Iteration 40, loss = 0.15441172
Iteration 41, loss = 0.15633894
Iteration 42, loss = 0.14787316
Iteration 43, loss = 0.14396440
Iteration 44, loss = 0.14045511
Iteration 45, loss = 0.13886535
Iteration 46, loss = 0.13986832
Iteration 47, loss = 0.13916150
Iteration 48, loss = 0.13460730
Iteration 49, loss = 0.13179115
Iteration 50, loss = 0.13219164
Iteration 51, loss = 0.12845386
Iteration 52, loss = 0.13031227
Iteration 53, loss = 0.12935392
Iteration 54, loss = 0.12279464
Iteration 55, loss = 0.11865279
Iteration 56, loss = 0.11567404
Iteration 57, loss = 0.11480718
Iteration 58, loss = 0.11310460
Iteration 59, loss = 0.10944328
Iteration 60, loss = 0.10784138
Iteration 61, loss = 0.10591418
Iteration 62, loss = 0.10309616
Iteration 63, loss = 0.11171684
Iteration 64, loss = 0.10576407
Iteration 65, loss = 0.10768576
Iteration 66, loss = 0.09803612
Iteration 67, loss = 0.09317136
Iteration 68, loss = 0.09053251
Iteration 69, loss = 0.08965136
Iteration 70, loss = 0.08866414
Iteration 71, loss = 0.08819369
Iteration 72, loss = 0.08486637
Iteration 73, loss = 0.08297076
Iteration 74, loss = 0.08020468
Iteration 75, loss = 0.07424465
Iteration 76, loss = 0.07287768
Iteration 77, loss = 0.07075976
Iteration 78, loss = 0.06991924
Iteration 79, loss = 0.06874959
Iteration 80, loss = 0.06393994
Iteration 81, loss = 0.06274615
Iteration 82, loss = 0.05972249
Iteration 83, loss = 0.06093153
Iteration 84, loss = 0.05983295
Iteration 85, loss = 0.06147624
Iteration 86, loss = 0.05584611
Iteration 87, loss = 0.05311711
Iteration 88, loss = 0.04963374
Iteration 89, loss = 0.05078703
Iteration 90, loss = 0.04631929
Iteration 91, loss = 0.04496915
Iteration 92, loss = 0.04349762
Iteration 93, loss = 0.04310213
Iteration 94, loss = 0.04028465
Iteration 95, loss = 0.03722716
Iteration 96, loss = 0.03611039
Iteration 97, loss = 0.03921828
Iteration 98, loss = 0.03735145
Iteration 99, loss = 0.03345479
Iteration 100, loss = 0.03072408
Iteration 101, loss = 0.03040565
Iteration 102, loss = 0.03791198
Iteration 103, loss = 0.03291577
Iteration 104, loss = 0.02743195
Iteration 105, loss = 0.02838975
Iteration 106, loss = 0.02606575
Iteration 107, loss = 0.02357008
Iteration 108, loss = 0.02394268
Iteration 109, loss = 0.02321250
Iteration 110, loss = 0.02172078
Iteration 111, loss = 0.02123483
Iteration 112, loss = 0.01886576
Iteration 113, loss = 0.01819287
Iteration 114, loss = 0.01716569
Iteration 115, loss = 0.01692574
Iteration 116, loss = 0.01817699
Iteration 117, loss = 0.01637771
Iteration 118, loss = 0.01534937
Iteration 119, loss = 0.01516282
Iteration 120, loss = 0.01408512
Iteration 121, loss = 0.01354129
Iteration 122, loss = 0.01374352
Iteration 123, loss = 0.01351730
Iteration 124, loss = 0.01375988
Iteration 125, loss = 0.01231833
Iteration 126, loss = 0.01143522
Iteration 127, loss = 0.01119774
Iteration 128, loss = 0.01077125
Iteration 129, loss = 0.00969596
Iteration 130, loss = 0.00976339
Iteration 131, loss = 0.00916933
Iteration 132, loss = 0.00863460
Iteration 133, loss = 0.00810387
Iteration 134, loss = 0.00801535
Iteration 135, loss = 0.00763076
Iteration 136, loss = 0.00725353
Iteration 137, loss = 0.00702537
Iteration 138, loss = 0.00679686
Iteration 139, loss = 0.00682545
Iteration 140, loss = 0.00649562
Iteration 141, loss = 0.00607521
Iteration 142, loss = 0.00586808
Iteration 143, loss = 0.00612258
Iteration 144, loss = 0.00582940
Iteration 145, loss = 0.00549396
Iteration 146, loss = 0.00525810
Iteration 147, loss = 0.00527221
Iteration 148, loss = 0.00532623
Iteration 149, loss = 0.00500656
Iteration 150, loss = 0.00504587
Iteration 151, loss = 0.00509467
Iteration 152, loss = 0.00468350
Iteration 153, loss = 0.00438997
Iteration 154, loss = 0.00438671
Iteration 155, loss = 0.00419848
Iteration 156, loss = 0.00407535
Iteration 157, loss = 0.00377495
Iteration 158, loss = 0.00359184
Iteration 159, loss = 0.00344644
Iteration 160, loss = 0.00339432
Iteration 161, loss = 0.00334510
Iteration 162, loss = 0.00336784
Iteration 163, loss = 0.00323166
Iteration 164, loss = 0.00310733
Iteration 165, loss = 0.00300088
Iteration 166, loss = 0.00295854
Iteration 167, loss = 0.00291164
Iteration 168, loss = 0.00288391
Iteration 169, loss = 0.00276364
Iteration 170, loss = 0.00261157
Iteration 171, loss = 0.00255657
Iteration 172, loss = 0.00252259
Iteration 173, loss = 0.00245652
Iteration 174, loss = 0.00248513
Iteration 175, loss = 0.00235571
Iteration 176, loss = 0.00228135
Iteration 177, loss = 0.00228095
Iteration 178, loss = 0.00221299
Iteration 179, loss = 0.00229950
Iteration 180, loss = 0.00222639
Iteration 181, loss = 0.00210776
Iteration 182, loss = 0.00216875
Iteration 183, loss = 0.00201565
Iteration 184, loss = 0.00189654
Iteration 185, loss = 0.00187350
Iteration 186, loss = 0.00186088
Iteration 187, loss = 0.00182498
Iteration 188, loss = 0.00174513
Iteration 189, loss = 0.00171778
Iteration 190, loss = 0.00170469
Iteration 191, loss = 0.00167389
Iteration 192, loss = 0.00168479
Iteration 193, loss = 0.00167795
Iteration 194, loss = 0.00159935
Iteration 195, loss = 0.00155316
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.

  model  accuracy  precision  recall      f1
0   MLP    0.8748     0.9438  0.8748  0.9017

## 9. Save results file

In [14]:
results.to_csv('RESULTS/models_results_ctgan.csv', index=False)
results

  model  accuracy  precision  recall      f1
0    RF    0.9043     0.9457  0.9043  0.9207
1   KNN    0.9146     0.9440  0.9146  0.9266
2    DT    0.8689     0.9414  0.8689  0.8975
3   SVM    0.7511     0.9394  0.7511  0.8204
4   MLP    0.8748     0.9438  0.8748  0.9017